class CatudyCopy {
  const CatudyCopy._();

  static String text(
    String languageCode,
    String key, [
    Map<String, Object?> values = const {},
  ]) {
    final source = languageCode == 'en' ? _en : _tr;
    var value = source[key] ?? _tr[key] ?? key;
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return value;
  }

  static const _tr = <String, String>{
    'common.cancel': 'İptal',
    'common.close': 'Kapat',
    'common.complete': 'Tamamla',
    'common.continue': 'Devam et',
    'common.done': 'Tamam',
    'common.daysShort': 'g',
    'common.minutes': 'dakika',
    'common.minutesShort': 'dk',
    'common.no': 'Hayır',
    'common.save': 'Kaydet',
    'common.selected': 'Seçili',
    'common.select': 'Seç',
    'common.yes': 'Evet',
    'common.gold': 'altın',
    'common.hoursShort': 's',
    'common.points': 'puan',
    'error.network':
        'Bağlantı kurulamadı. İnternetini kontrol edip tekrar dene.',
    'error.auth': 'Giriş bilgilerini kontrol edip tekrar dene.',
    'auth.genericError': 'Giriş işlemi tamamlanamadı. Biraz sonra tekrar dene.',
    'lobby.genericError': 'Lobi işlemi tamamlanamadı. Biraz sonra tekrar dene.',

    'auth.title': 'Giriş',
    'auth.subtitle': 'Catudy hesabına gir, lobileri ve ilerlemeyi eşitle.',
    'auth.displayName': 'Görünen ad',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.signIn': 'E-posta ile giriş',
    'auth.signUp': 'E-posta ile kayıt ol',
    'auth.haveAccount': 'Hesabım var',
    'auth.needAccount': 'Yeni hesap aç',
    'auth.google': 'Google ile devam et',
    'auth.apple': 'Apple ile devam et',
    'auth.guest': 'Misafir olarak devam et',
    'auth.displayNameRequired': 'Kayıt olmak için görünen ad gir.',
    'auth.offlineUnavailable':
        'Online giriş için Supabase bağlantısı gerekiyor.',

    'nav.home': 'Ana ekran',
    'nav.stats': 'İstatistik',
    'nav.calendar': 'Takvim',
    'nav.pet': 'Pet',
    'nav.social': 'Sosyal',
    'nav.profile': 'Profil',

    'home.greeting': 'İyi günler!',
    'home.petButton': 'Pet',
    'home.focusTime': 'Odak Zamanı',
    'home.createLobby': 'Lobi Kur',
    'home.joinLobby': 'Lobiye Katıl',
    'home.todaySummary': 'Bugünün Özeti',
    'home.focus': 'Odak',
    'home.streak': 'Seri',
    'home.noSessions': 'Henüz kayıtlı seans yok',
    'home.lastSession': 'Son Seans: {minutes} dk',
    'home.todayReminders': 'Bugünkü Hatırlatmalar',
    'home.noTodayReminders': 'Bugün için hatırlatma yok.',
    'home.breakTitle': 'Kısa mola zamanı!',
    'home.breakBody': 'Biraz dinlen, sonra yeniden odaklan.',
    'home.happiness': 'Mutluluk',
    'home.hunger': 'Açlık',
    'home.good': 'İyi',
    'home.normal': 'Normal',
    'home.full': 'Tok',
    'home.hungry': 'Aç',
    'home.focusSuggestion': '{category} için {minutes} dakika çalışabilirsin.',
    'home.focusSuggestionReason':
        'Önceki {sessions} seansına göre bu ritim daha verimli görünüyor.',
    'home.focusSuggestionStarter':
        'İlk öneri için dengeli bir başlangıç süresi seçildi.',
    'home.prepareFocusPlan': 'Planı Hazırla',
    'home.dailyGoal': 'Günlük hedef',
    'home.dailyGoalProgress': '{done}/{goal} dk tamamlandı. Kalan: {left} dk.',
    'home.editDailyGoal': 'Günlük hedefi düzenle',
    'home.goalMinutes': 'Hedef dakika',

    'achievements.title': 'Başarımlar',

    'social.title': 'Sosyal',
    'social.challengeProgress':
        '{done}/{goal} dk tamamlandı. Kalan {left} dk. Katılımcı: {people}',
    'social.friends': 'Arkadaşlar',
    'social.noFriends': 'Henüz arkadaş eklenmedi.',
    'social.addFriend': 'Arkadaş ekle',
    'social.sendFriendRequest': 'Arkadaşlık isteği gönder',
    'social.removeFriend': 'Arkadaştan çıkar',
    'social.visitProfile': 'Profili ziyaret et',
    'social.visitPetRoom': 'Pet odasını ziyaret et',
    'social.addByNameTitle': 'Kod ile arkadaş ekle',
    'social.friendSearchLabel': 'Kullanıcı kodu',
    'social.friendSearchHint': 'Örn. CAT-1A2B-9F8E',
    'social.requestButton': 'İstek gönder',
    'social.friendAdded': 'Arkadaş eklendi.',
    'social.friendRequestSent': 'Arkadaşlık isteği gönderildi.',
    'social.friendRequestPending': 'Bu kullanıcıyla bekleyen bir istek var.',
    'social.friendAlreadyAdded': 'Bu kullanıcı zaten arkadaş listende.',
    'social.friendSelf': 'Kendini arkadaş olarak ekleyemezsin.',
    'social.friendNotFound': 'Bu kullanıcı bulunamadı.',
    'social.friendBlocked': 'Bu kullanıcı engellenmiş.',
    'social.friendEmpty': 'Bir kullanıcı kodu gir.',
    'social.friendRequests': 'Arkadaşlık istekleri',
    'social.noFriendRequests': 'Bekleyen arkadaşlık isteği yok.',
    'social.incomingRequestFrom': '{name} arkadaşlık isteği gönderdi.',
    'social.outgoingRequestTo': '{name} için istek bekliyor.',
    'social.pending': 'Bekliyor',
    'social.cancelRequest': 'İsteği iptal et',
    'social.moreActions': 'Diğer işlemler',
    'social.removeFriendAction': 'Arkadaştan çıkar',
    'social.blockUser': 'Engelle',
    'social.reportUser': 'Şikayet et',
    'social.friendRemoved': 'Arkadaşlıktan çıkarıldı.',
    'social.requestCancelled': 'İstek iptal edildi.',
    'social.userBlocked': 'Kullanıcı engellendi.',
    'social.userReported': 'Şikayet kaydedildi.',
    'social.inviteToLobby': 'Davet et',
    'social.createLobbyFirst': 'Önce lobi kur. Seni lobi ekranına götürüyorum.',
    'social.lobbyInviteReady': 'Lobi daveti hazır.',

    'leaderboard.title': 'Leaderboard',
    'leaderboard.body':
        'Canlı odak puanı sıralaması. Buradan profilleri ve pet odalarını ziyaret edebilirsin.',
    'leaderboard.you': 'sen',
    'leaderboard.roomSoon': 'Pet odasını ziyaret et',
    'leaderboard.visitSoon': 'Pet odasını ziyaret et',

    'calendar.title': 'Takvim',
    'calendar.manualAdd': 'Manuel Ekle',
    'calendar.reminderAdd': 'Hatırlatma',
    'calendar.reminders': 'Hatırlatmalar',
    'calendar.noReminders': 'Bugün için hatırlatma yok.',
    'calendar.records': 'Kayıtlar',
    'calendar.noRecords': 'Bugüne ait kayıt yok.',
    'calendar.pastInfo': 'Geçmiş gün: sadece manuel kayıt eklenebilir.',
    'calendar.todayInfo': 'Bugün: manuel kayıt ve hatırlatma eklenebilir.',
    'calendar.futureInfo': 'Gelecek gün: sadece hatırlatma eklenebilir.',
    'calendar.reminderTitle': 'Hatırlatma',
    'calendar.reminderText': 'Hatırlatma metni',
    'calendar.reminderHint': 'Örn. Matematik tekrarını bitir',
    'calendar.enterText': 'Metin gir.',
    'calendar.time': 'Saat: {time}',

    'manual.title': 'Manuel Kayıt',
    'manual.info': 'Manuel kayıtlar açıkça etiketlenir ve ödül kazandırmaz.',
    'manual.category': 'Kategori',
    'manual.minutes': 'Dakika',
    'manual.note': 'Not',
    'manual.save': 'Manuel kaydı kaydet',

    'stats.title': 'İstatistik',
    'stats.categoryDistribution': 'Kategori Dağılımı',
    'stats.noRecordsRange': 'Bu aralıkta kayıt yok.',
    'stats.focusGarden': 'Odak Bahçesi',
    'stats.focus': 'Odak',
    'stats.sessions': 'Seans',
    'stats.streak': 'Seri',
    'stats.week': 'Hafta',
    'stats.month': 'Ay',
    'stats.all': 'Tümü',
    'stats.total': 'toplam',
    'stats.manualNote':
        'Manuel kayıtlar raporda görünür, ancak altın ve leaderboard kredisi vermez.',
    'stats.insights': 'İçgörüler',
    'stats.averageSession': 'Ortalama seans',
    'stats.bestHour': 'En verimli saat',
    'stats.todayGoal': 'Bugünkü hedef',
    'stats.weeklyProgress': 'Haftalık ilerleme',
    'stats.monthlyProgress': 'Aylık ilerleme',
    'stats.allTimeProgress': 'Tüm zaman ilerlemesi',
    'stats.lastSevenDays': 'Son 7 gün',
    'stats.thisMonth': 'Bu ay',
    'stats.allRecords': 'Tüm kayıtlar',
    'stats.periodTotalMinutes': 'Toplam: {minutes} dk',

    'focus.categoryTitle': 'Kategori Seç',
    'focus.addCategoryClose': 'Kategori eklemeyi kapat',
    'focus.addCategoryOpen': 'Yeni kategori ekle',
    'focus.customCategory': 'Özel kategori',
    'focus.categoryName': 'Kategori adı',
    'focus.addCategory': 'Kategori ekle',
    'focus.tapSelect': 'Dokun ve seç',
    'focus.durationTitle': 'Süre Seç',
    'focus.durationInfo':
        'Odak süresini seç. Tamamlandığında ödül, pet durumu, istatistik ve takvim güncellenir.',
    'focus.customDuration': 'Özel süre',
    'focus.customMinutes': 'Dakika',
    'focus.selectedDuration': 'Seçili süre: {minutes} dakika',
    'focus.taskTitle': 'Odak görevi',
    'focus.noOpenTasks': 'Yaklaşan açık görev yok.',
    'focus.selectTask': 'Görev seç',
    'focus.noTaskSelected': 'Görevsiz odak',
    'focus.startTimer': 'Timer başlat',
    'focus.start': 'Odak başlat',
    'focus.timerTitle': 'Odak Timer',
    'focus.lobbyTimerTitle': 'Lobi Timer',
    'focus.noActiveSession': 'Aktif seans yok. Yeni bir odak seansı başlat.',
    'focus.endFocus': 'Odağı Bitir',
    'focus.restoreInfo': 'Seans zaman damgasından geri yüklenir.',
    'focus.resultTitle': 'Seans Sonucu',
    'focus.resultEmpty': 'Henüz sonuç yok',
    'focus.resultComplete': 'Odak tamamlandı',
    'focus.resultEmptyBody': 'Ödül kazanmak için bir seans başlatıp tamamla.',
    'focus.resultSaved': '{category} için {minutes} dakika kaydedildi.',
    'focus.seeStats': 'İstatistikleri gör',
    'focus.openShop': 'Mağazayı aç',
    'focus.petUnlocked': 'Yeni pet açıldı',
    'focus.petUnlockedBody': '{pet} envantere eklendi.',
    'focus.resultSummary': 'Seans özeti',
    'focus.resultPointsEarned': 'Kazanılan puan',
    'focus.resultPetEffect': 'Pet etkisi',
    'focus.resultPetEffectValue': '+8 mutluluk',
    'focus.resultStreak': 'Seri durumu',
    'focus.resultStreakValue': '{days} gün seri',
    'focus.resultGoal': 'Günlük hedef',
    'focus.focusAgain': 'Tekrar odaklan',

    'pet.room': 'Pet Odası',
    'pet.roomName': '{pet} Odası',
    'pet.roomSubtitle': 'Mochi burada dinlenir, bekler ve seninle çalışır.',
    'pet.noCosmetic': 'Takılı kozmetik yok',
    'pet.shop': 'Mağaza',
    'pet.inventory': 'Envanter',
    'pet.returnMyRoom': 'Kendi odama dön',
    'pet.showTour': 'Turu tekrar göster',
    'pet.settings': 'Ayarlar',
    'pet.mood': 'Mutluluk',
    'pet.energy': 'Enerji',
    'pet.roomBoost': 'Oda boostu',
    'pet.roomMaintenanceTitle': 'Oda yenileniyor',
    'pet.roomMaintenanceBody':
        'Bu alan şu an inşaat halinde; bazı eşyalar yerinden oynayabilir.',
    'pet.nameDialogTitle': 'Petinin ismi ne olsun?',
    'pet.nameDialogBody':
        'İstersen önerilerden birini seçebilir ya da kendi ismini yazabilirsin.',
    'pet.nameField': 'Pet ismi',
    'pet.nameSave': 'İsmi kaydet',

    'shop.title': 'Mağaza',
    'shop.petUnlocks': 'Pet Kilitleri',
    'shop.roomFurniture': 'Oda Mobilyaları',
    'shop.cosmetics': 'Kozmetikler',
    'shop.rewardBoost': 'odak ödülü',
    'shop.owned': 'Alındı',
    'shop.buy': 'Al',
    'shop.openInventory': 'Envanteri aç',
    'shop.unlocked': 'Açık',

    'item.violet_collar.name': 'Mor Tasma',
    'item.violet_collar.description': 'Mochi için yumuşak bir pet kozmetiği.',
    'item.focus_badge.name': 'Odak Rozeti',
    'item.focus_badge.description': 'Herkese açık profilinde gösterilir.',
    'item.sunny_hat.name': 'Güneş Şapkası',
    'item.sunny_hat.description': 'Pet odası için sıcak bir kozmetik.',
    'item.soft_study_nook.name': 'Yumuşak Çalışma Alanı',
    'item.soft_study_nook.description':
        'Mochi için minderli, alçak bir çalışma köşesi.',
    'item.moonlit_study_nook.name': 'Ay Işıklı Çalışma Alanı',
    'item.moonlit_study_nook.description':
        'Odak seanslarında defter ve ışığıyla öne çıkan alan.',
    'item.cloud_nap_bed.name': 'Bulut Yatak',
    'item.cloud_nap_bed.description':
        'Odanın sağ köşesine yerleşen yumuşak uyku alanı.',
    'item.warm_den_bed.name': 'Sıcak Yuva Yatağı',
    'item.warm_den_bed.description':
        'Daha derin gölgeli, konforlu bir pet yatağı.',
    'item.glow_lantern.name': 'Parlayan Oda Lambası',
    'item.glow_lantern.description':
        'Odanın derinliğini güçlendiren küçük bir ışık.',
    'item.tiny_library_shelf.name': 'Mini Kitaplık',
    'item.tiny_library_shelf.description':
        'Çalışma alanının arkasına küçük kitap rafları ekler.',

    'inventory.title': 'Envanter',
    'inventory.pets': 'Petler',
    'inventory.equipped': 'Tak',
    'inventory.roomEquipped': 'Odada yerinde',
    'inventory.roomFurniture': 'Oda mobilyası',
    'inventory.petEquipped': 'Pet üzerinde takılı',
    'inventory.petCosmetic': 'Pet kozmetiği',
    'inventory.profileEquipped': 'Profilde takılı',
    'inventory.profileCosmetic': 'Profil kozmetiği',

    'profile.title': 'Profil',
    'profile.subtitle': 'Odak meraklısı ve çalışma dostu',
    'profile.petMessage':
        'Bugün biraz daha odaklan, {pet} biraz daha mutlu olsun.',
    'profile.totalFocus': 'Toplam Odak',
    'profile.sessions': 'Seans',
    'profile.equippedItems': 'Takılı Eşyalar',
    'profile.noItems': 'Henüz eşya yok.',
    'profile.viewAll': 'Tümünü Gör',
    'profile.myPet': 'Petim',
    'profile.focusBuddy': 'Odak Dostu',
    'profile.petRoom': 'Pet Odası',
    'profile.favoriteCategory': 'Favori Kategori',
    'profile.weeklySummary': 'Haftalık Özet',
    'profile.dailyFocus': 'Günlük odak',
    'profile.edit': 'Profili Düzenle',
    'profile.share': 'Profil linkini paylaş',
    'profile.shareSubject': '{name} Catudy profili',
    'profile.shareText': '{name} Catudy profilini paylaştı: {link}',
    'profile.shareCopied':
        'Paylaşım açılamadı, profil linki panoya kopyalandı.',
    'profile.copyId': 'Kodumu kopyala',
    'profile.idCopied': 'Kullanıcı kodu kopyalandı.',
    'profile.myId': 'Kullanıcı kodu',
    'profile.editTitle': 'Profili Düzenle',
    'profile.chooseAvatar': 'Profil resmi seç',
    'profile.uploadAvatar': 'Özel resim yükle',
    'profile.saveProfile': 'Profili kaydet',
    'profile.name': 'İsim',
    'profile.publicTitle': 'Herkese Açık Profil',
    'profile.publicBody':
        'Herkese açık görünüm özel ayarları, token bilgisini ve sync metadatasını göstermez.',
    'profile.thisWeek': 'Bu hafta {minutes} dk',
    'profile.favorite': 'Favori: {category}',
    'profile.richStats': 'Profil özeti',
    'profile.bestStreak': 'En iyi seri: {days}g',
    'profile.todayGoalShort': 'Bugün {done}/{goal} dk',
    'profile.badges': 'Rozetler',
    'profile.noBadges': 'Henüz açılmış rozet yok.',
    'profile.publicStatsTitle': 'Profil istatistikleri',
    'profile.publicStatsHidden':
        'Bu kullanıcı profil istatistiklerini gizli tutuyor.',
    'profile.sessionsPublic': '{count} seans',
    'profile.totalPublic': 'Toplam {minutes} dk',

    'settings.title': 'Ayarlar',
    'settings.displayName': 'Görünen ad',
    'settings.profileShareBaseUrl': 'Profil paylaşım adresi',
    'settings.profileShareBaseUrlHint': 'Örn. https://senin-domainin.com',
    'settings.privacy': 'Gizlilik',
    'settings.profileStatsVisibility': 'Profilde istatistikleri göster',
    'settings.profileStatsVisibilityBody':
        'Kapalıyken profilini ziyaret edenler toplam süre, seri ve seans bilgilerini görmez.',
    'settings.blockedUsers': 'Engellenen kullanıcılar',
    'settings.noBlockedUsers': 'Engellenen kullanıcı yok.',
    'settings.unblock': 'Engeli kaldır',
    'settings.language': 'Dil',
    'settings.turkish': 'Türkçe',
    'settings.english': 'English',
    'settings.theme': 'Tema',
    'settings.system': 'Sistem',
    'settings.light': 'Aydınlık',
    'settings.dark': 'Gece modu',
    'settings.dnd': 'Rahatsız etmeyin hatırlatıcısı',
    'settings.petNotifications': 'Pet bildirimleri',
    'settings.dailyGoalReminder': 'Günlük hedef hatırlatması',
    'settings.dailyGoalReminderBody': 'Her gün {time} saatinde hatırlat.',
    'settings.changeReminderTime': 'Hatırlatma saatini değiştir',
    'settings.save': 'Ayarları kaydet',
    'settings.saved': 'Ayarlar kaydedildi',
    'settings.offline':
        'Çevrim dışı kullanım açık. Veriler bu cihazda tutuluyor.',
    'settings.server': 'Senkronizasyon açık.',
    'settings.authTitle': 'Hesap',
    'settings.authSignedIn': '{provider} ile giriş yapıldı: {email}',
    'settings.authSignedOut': 'Henüz giriş yapılmadı.',
    'settings.signOut': 'Çıkış yap',
    'settings.openLogin': 'Giriş ekranını aç',
    'settings.demoWallet': 'Demo Bakiyesi',
    'settings.demoWalletBody':
        'Mağaza denemeleri için altını 5000, puanı 2500 seviyesine tamamlar. Satın alınan eşyaları sıfırlamaz.',
    'settings.demoWalletButton': 'Demo bakiyesi yükle',
    'settings.demoWalletLoaded': 'Demo bakiyesi yüklendi.',

    'lobby.title': 'Lobi',
    'lobby.chooseFlow':
        'Lobi kurmak veya mevcut bir lobiye katılmak için seçim yap.',
    'lobby.createTitle': 'Lobi Kur',
    'lobby.joinTitle': 'Lobiye Katıl',
    'lobby.roomTitle': 'Lobi Odası',
    'lobby.durationSetup': 'Odak süresini seç veya elle dakika gir.',
    'lobby.customMinutes': 'Dakika',
    'lobby.selectedDuration': 'Seçili süre: {minutes} dakika',
    'lobby.noActiveLobby': 'Aktif lobi yok. Önce lobi kur veya koda katıl.',
    'lobby.copyCode': 'Kodu kopyala',
    'lobby.codeCopied': 'Lobi kodu kopyalandı.',
    'lobby.shareInvite': 'Lobi daveti paylaş',
    'lobby.inviteText': 'Catudy lobime katıl. Kod: {code}',
    'lobby.code': 'Katılım kodu: {code}',
    'lobby.onlineBackend': 'Online lobi aktif. Durum Supabase ile eşitlenir.',
    'lobby.offlineBackend':
        'Supabase ayarı yok. Şimdilik demo/offline lobi kullanılıyor.',
    'lobby.create': 'Online lobi kur',
    'lobby.join': 'Koda katıl',
    'lobby.joinCode': 'Lobi kodu',
    'lobby.leave': 'Lobiden çık',
    'lobby.enterCode': 'Lobi kodu gir.',
    'lobby.demoMode':
        'Online ayar bulunamadığı için demo lobi açıldı. Gerçek lobi için Supabase URL ve anon key gerekiyor.',
    'lobby.onlyOwnerCanStart': 'Sadece lobi kurucusu seansı başlatabilir.',
    'lobby.waitForSecondMember': 'Başlatmak için lobide en az iki kişi olmalı.',
    'lobby.waitForReady': 'Başlatmak için herkes hazır olmalı.',
    'lobby.owner': 'kurucu',
    'lobby.online': 'çevrim içi',
    'lobby.offline': 'çevrim dışı',
    'lobby.notReady': 'Hazır değil',
    'lobby.ready': 'Hazır',
    'lobby.start': 'Senkron başlat',
    'lobby.breakVote': 'Mola oylaması',
    'lobby.breakVoteStatus': 'Evet: {yes}/{total} · Hayır: {no}/{total}',
    'lobby.breakQuestion': 'Molaya çıkılsın mı? Oylar lobiyle eşitlenir.',

    'tour.barrier': 'Catudy tanıtım turu',
    'tour.homeTitle': 'Burası ana ekran',
    'tour.homeBody':
        'Bugünün odak süresini, serini, hatırlatmalarını ve petinin kısa durumunu buradan takip edersin.',
    'tour.focusTitle': 'Odak burada başlar',
    'tour.focusBody':
        'Ortadaki saat düğmesine basınca kategori ve süre seçimine geçersin. Gerçek seanslar puan, altın ve pet gelişimi kazandırır.',
    'tour.calendarTitle': 'Takvim',
    'tour.calendarBody':
        'Takvim ekranında geçmiş günlere manuel kayıt ekleyebilir, bugün ve gelecek günler için kendi metninle hatırlatma oluşturabilirsin.',
    'tour.statsTitle': 'İstatistikler',
    'tour.statsBody':
        'Hafta, ay ve tüm zaman aralıklarında odak ritmini görürsün. Grafiklere dokununca kısa açıklamalar açılır.',
    'tour.petTitle': 'Pet odası',
    'tour.petBody':
        'Mochi burada yaşar. Mutluluk, açlık ve enerji barlarına dokunarak ne anlama geldiklerini görebilirsin.',
    'tour.profileTitle': 'Profil',
    'tour.profileBody':
        'Toplam odak, seans sayısı, favori kategori, takılı eşyalar ve pet özetin burada görünür.',
    'onboarding.nameTitle': 'Önce seni tanıyalım',
    'onboarding.nameBody':
        'Profilinde ve lobilerde görünecek adı seç. Bunu daha sonra profilden değiştirebilirsin.',
    'onboarding.petTitle': 'Petini seç',
    'onboarding.petBody':
        'Mochi başlangıç dostun. Puan kazandıkça yeni petlerin kilidi açılır.',
    'onboarding.goalTitle': 'Günlük hedef',
    'onboarding.goalBody':
        'Bugün için gerçekçi bir odak dakikası hedefi belirle.',
    'onboarding.friendTitle': 'Arkadaş kodu',
    'onboarding.friendBody': 'Arkadaşların seni eklemek için bu kodu kullanır.',
    'onboarding.startTitle': 'İlk odağa hazır',
    'onboarding.startBody':
        'Kategori ve süre seçerek ilk odak seansını başlatabilirsin.',
    'onboarding.startFocus': 'İlk odağı başlat',
    'tour.skip': 'Geç',
    'tour.finish': 'Bitir',
    'tour.next': 'Sonraki',
  };

  static const _en = <String, String>{
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.complete': 'Complete',
    'common.continue': 'Continue',
    'common.done': 'OK',
    'common.daysShort': 'd',
    'common.minutes': 'minutes',
    'common.minutesShort': 'min',
    'common.no': 'No',
    'common.save': 'Save',
    'common.selected': 'Selected',
    'common.select': 'Select',
    'common.yes': 'Yes',
    'common.gold': 'gold',
    'common.hoursShort': 'h',
    'common.points': 'points',
    'error.network': 'Could not connect. Check your internet and try again.',
    'error.auth': 'Check your sign-in details and try again.',
    'auth.genericError': 'Sign-in could not be completed. Try again shortly.',
    'lobby.genericError':
        'Lobby action could not be completed. Try again shortly.',

    'auth.title': 'Sign in',
    'auth.subtitle': 'Sign in to Catudy and sync lobbies and progress.',
    'auth.displayName': 'Display name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign in with email',
    'auth.signUp': 'Sign up with email',
    'auth.haveAccount': 'I have an account',
    'auth.needAccount': 'Create account',
    'auth.google': 'Continue with Google',
    'auth.apple': 'Continue with Apple',
    'auth.guest': 'Continue as guest',
    'auth.displayNameRequired': 'Enter a display name to create an account.',
    'auth.offlineUnavailable':
        'Supabase connection is required for online auth.',

    'nav.home': 'Home',
    'nav.stats': 'Stats',
    'nav.calendar': 'Calendar',
    'nav.pet': 'Pet',
    'nav.social': 'Social',
    'nav.profile': 'Profile',

    'home.greeting': 'Have a good day!',
    'home.petButton': 'Pet',
    'home.focusTime': 'Focus Time',
    'home.createLobby': 'Create Lobby',
    'home.joinLobby': 'Join Lobby',
    'home.todaySummary': "Today's Summary",
    'home.focus': 'Focus',
    'home.streak': 'Streak',
    'home.noSessions': 'No sessions yet',
    'home.lastSession': 'Last Session: {minutes} min',
    'home.todayReminders': "Today's Reminders",
    'home.noTodayReminders': 'No reminders for today.',
    'home.breakTitle': 'Short break time!',
    'home.breakBody': 'Rest a little, then focus again.',
    'home.happiness': 'Happiness',
    'home.hunger': 'Hunger',
    'home.good': 'Good',
    'home.normal': 'Normal',
    'home.full': 'Full',
    'home.hungry': 'Hungry',
    'home.focusSuggestion': 'You can study {category} for {minutes} minutes.',
    'home.focusSuggestionReason':
        'Based on your last {sessions} sessions, this rhythm looks more efficient.',
    'home.focusSuggestionStarter':
        'A balanced starter duration was selected for the first recommendation.',
    'home.prepareFocusPlan': 'Prepare Plan',
    'home.dailyGoal': 'Daily target',
    'home.dailyGoalProgress':
        '{done}/{goal} min completed. Remaining: {left} min.',
    'home.editDailyGoal': 'Edit daily target',
    'home.goalMinutes': 'Target minutes',

    'achievements.title': 'Achievements',

    'social.title': 'Social',
    'social.challengeProgress':
        '{done}/{goal} min completed. {left} min left. People: {people}',
    'social.friends': 'Friends',
    'social.noFriends': 'No friends added yet.',
    'social.addFriend': 'Add friend',
    'social.sendFriendRequest': 'Send friend request',
    'social.removeFriend': 'Remove friend',
    'social.visitProfile': 'Visit profile',
    'social.visitPetRoom': 'Visit pet room',
    'social.addByNameTitle': 'Add friend by code',
    'social.friendSearchLabel': 'User code',
    'social.friendSearchHint': 'E.g. CAT-1A2B-9F8E',
    'social.requestButton': 'Send request',
    'social.friendAdded': 'Friend added.',
    'social.friendRequestSent': 'Friend request sent.',
    'social.friendRequestPending':
        'There is already a pending request with this user.',
    'social.friendAlreadyAdded': 'This user is already in your friends list.',
    'social.friendSelf': 'You cannot add yourself as a friend.',
    'social.friendNotFound': 'User not found.',
    'social.friendBlocked': 'This user is blocked.',
    'social.friendEmpty': 'Enter a user code.',
    'social.friendRequests': 'Friend requests',
    'social.noFriendRequests': 'No pending friend requests.',
    'social.incomingRequestFrom': '{name} sent a friend request.',
    'social.outgoingRequestTo': 'Request pending for {name}.',
    'social.pending': 'Pending',
    'social.cancelRequest': 'Cancel request',
    'social.moreActions': 'More actions',
    'social.removeFriendAction': 'Remove friend',
    'social.blockUser': 'Block',
    'social.reportUser': 'Report',
    'social.friendRemoved': 'Friend removed.',
    'social.requestCancelled': 'Request cancelled.',
    'social.userBlocked': 'User blocked.',
    'social.userReported': 'Report saved.',
    'social.inviteToLobby': 'Invite',
    'social.createLobbyFirst':
        'Create a lobby first. Taking you to the lobby screen.',
    'social.lobbyInviteReady': 'Lobby invite is ready.',

    'leaderboard.title': 'Leaderboard',
    'leaderboard.body':
        'Live ranking by focus points. You can visit profiles and pet rooms from here.',
    'leaderboard.you': 'you',
    'leaderboard.roomSoon': 'Visit pet room',
    'leaderboard.visitSoon': 'Visit pet room',

    'calendar.title': 'Calendar',
    'calendar.manualAdd': 'Add Manual',
    'calendar.reminderAdd': 'Reminder',
    'calendar.reminders': 'Reminders',
    'calendar.noReminders': 'No reminders for this day.',
    'calendar.records': 'Records',
    'calendar.noRecords': 'No records for this day.',
    'calendar.pastInfo': 'Past day: only manual records can be added.',
    'calendar.todayInfo': 'Today: manual records and reminders can be added.',
    'calendar.futureInfo': 'Future day: only reminders can be added.',
    'calendar.reminderTitle': 'Reminder',
    'calendar.reminderText': 'Reminder text',
    'calendar.reminderHint': 'E.g. finish math review',
    'calendar.enterText': 'Enter text.',
    'calendar.time': 'Time: {time}',

    'manual.title': 'Manual Record',
    'manual.info':
        'Manual records are clearly labeled and do not give rewards.',
    'manual.category': 'Category',
    'manual.minutes': 'Minutes',
    'manual.note': 'Note',
    'manual.save': 'Save manual record',

    'stats.title': 'Stats',
    'stats.categoryDistribution': 'Category Distribution',
    'stats.noRecordsRange': 'No records in this range.',
    'stats.focusGarden': 'Focus Garden',
    'stats.focus': 'Focus',
    'stats.sessions': 'Sessions',
    'stats.streak': 'Streak',
    'stats.week': 'Week',
    'stats.month': 'Month',
    'stats.all': 'All',
    'stats.total': 'total',
    'stats.manualNote':
        'Manual records appear in reports, but do not give gold or leaderboard credit.',
    'stats.insights': 'Insights',
    'stats.averageSession': 'Average session',
    'stats.bestHour': 'Best hour',
    'stats.todayGoal': "Today's target",
    'stats.weeklyProgress': 'Weekly progress',
    'stats.monthlyProgress': 'Monthly progress',
    'stats.allTimeProgress': 'All-time progress',
    'stats.lastSevenDays': 'Last 7 days',
    'stats.thisMonth': 'This month',
    'stats.allRecords': 'All records',
    'stats.periodTotalMinutes': 'Total: {minutes} min',

    'focus.categoryTitle': 'Choose Category',
    'focus.addCategoryClose': 'Close category form',
    'focus.addCategoryOpen': 'Add new category',
    'focus.customCategory': 'Custom category',
    'focus.categoryName': 'Category name',
    'focus.addCategory': 'Add category',
    'focus.tapSelect': 'Tap to select',
    'focus.durationTitle': 'Choose Duration',
    'focus.durationInfo':
        'Choose focus duration. Rewards, pet state, stats, and calendar update when it is complete.',
    'focus.customDuration': 'Custom duration',
    'focus.customMinutes': 'Minutes',
    'focus.selectedDuration': 'Selected duration: {minutes} minutes',
    'focus.taskTitle': 'Focus task',
    'focus.noOpenTasks': 'No upcoming open tasks.',
    'focus.selectTask': 'Select task',
    'focus.noTaskSelected': 'Focus without a task',
    'focus.startTimer': 'Start timer',
    'focus.start': 'Start focus',
    'focus.timerTitle': 'Focus Timer',
    'focus.lobbyTimerTitle': 'Lobby Timer',
    'focus.noActiveSession': 'No active session. Start a new focus session.',
    'focus.endFocus': 'End Focus',
    'focus.restoreInfo': 'Session restores from its timestamp.',
    'focus.resultTitle': 'Session Result',
    'focus.resultEmpty': 'No result yet',
    'focus.resultComplete': 'Focus complete',
    'focus.resultEmptyBody': 'Start and complete a session to earn rewards.',
    'focus.resultSaved': '{minutes} minutes saved for {category}.',
    'focus.seeStats': 'See stats',
    'focus.openShop': 'Open shop',
    'focus.petUnlocked': 'New pet unlocked',
    'focus.petUnlockedBody': '{pet} was added to inventory.',
    'focus.resultSummary': 'Session summary',
    'focus.resultPointsEarned': 'Points earned',
    'focus.resultPetEffect': 'Pet effect',
    'focus.resultPetEffectValue': '+8 happiness',
    'focus.resultStreak': 'Streak status',
    'focus.resultStreakValue': '{days} day streak',
    'focus.resultGoal': 'Daily target',
    'focus.focusAgain': 'Focus again',

    'pet.room': 'Pet Room',
    'pet.roomName': "{pet}'s Room",
    'pet.roomSubtitle': 'Mochi rests, waits, and studies with you here.',
    'pet.noCosmetic': 'No cosmetic equipped',
    'pet.shop': 'Shop',
    'pet.inventory': 'Inventory',
    'pet.returnMyRoom': 'Return to my room',
    'pet.showTour': 'Show tour again',
    'pet.settings': 'Settings',
    'pet.mood': 'Happiness',
    'pet.energy': 'Energy',
    'pet.roomBoost': 'Room boost',
    'pet.roomMaintenanceTitle': 'Room refresh in progress',
    'pet.roomMaintenanceBody':
        'This room is under construction, so a few details may shift for now.',
    'pet.nameDialogTitle': 'What should your pet be called?',
    'pet.nameDialogBody': 'Pick a suggestion or type your own pet name.',
    'pet.nameField': 'Pet name',
    'pet.nameSave': 'Save name',

    'shop.title': 'Shop',
    'shop.petUnlocks': 'Pet Unlocks',
    'shop.roomFurniture': 'Room Furniture',
    'shop.cosmetics': 'Cosmetics',
    'shop.rewardBoost': 'focus reward',
    'shop.owned': 'Owned',
    'shop.buy': 'Buy',
    'shop.openInventory': 'Open inventory',
    'shop.unlocked': 'Unlocked',

    'item.violet_collar.name': 'Violet Collar',
    'item.violet_collar.description': 'A soft pet cosmetic for Mochi.',
    'item.focus_badge.name': 'Focus Badge',
    'item.focus_badge.description': 'Shown on your public profile.',
    'item.sunny_hat.name': 'Sunny Hat',
    'item.sunny_hat.description': 'A warm cosmetic for Pet Room.',
    'item.soft_study_nook.name': 'Soft Study Nook',
    'item.soft_study_nook.description':
        'A cushioned low study corner made for Mochi.',
    'item.moonlit_study_nook.name': 'Moonlit Study Nook',
    'item.moonlit_study_nook.description':
        'A notebook and moon lamp setup for focus sessions.',
    'item.cloud_nap_bed.name': 'Cloud Nap Bed',
    'item.cloud_nap_bed.description':
        'A soft sleeping spot placed in the right corner.',
    'item.warm_den_bed.name': 'Warm Den Bed',
    'item.warm_den_bed.description':
        'A cozier pet bed with deeper shadows and padding.',
    'item.glow_lantern.name': 'Glow Lantern',
    'item.glow_lantern.description':
        'A small light that makes the room feel deeper.',
    'item.tiny_library_shelf.name': 'Tiny Library Shelf',
    'item.tiny_library_shelf.description':
        'Adds compact book shelves behind the study area.',

    'inventory.title': 'Inventory',
    'inventory.pets': 'Pets',
    'inventory.equipped': 'Equip',
    'inventory.roomEquipped': 'Placed in room',
    'inventory.roomFurniture': 'Room furniture',
    'inventory.petEquipped': 'Equipped on pet',
    'inventory.petCosmetic': 'Pet cosmetic',
    'inventory.profileEquipped': 'Equipped on profile',
    'inventory.profileCosmetic': 'Profile cosmetic',

    'profile.title': 'Profile',
    'profile.subtitle': 'Focus enthusiast and study buddy',
    'profile.petMessage':
        'Focus a little more today and {pet} will be happier.',
    'profile.totalFocus': 'Total Focus',
    'profile.sessions': 'Sessions',
    'profile.equippedItems': 'Equipped Items',
    'profile.noItems': 'No items yet.',
    'profile.viewAll': 'View All',
    'profile.myPet': 'My Pet',
    'profile.focusBuddy': 'Focus Buddy',
    'profile.petRoom': 'Pet Room',
    'profile.favoriteCategory': 'Favorite Category',
    'profile.weeklySummary': 'Weekly Summary',
    'profile.dailyFocus': 'Daily focus',
    'profile.edit': 'Edit Profile',
    'profile.share': 'Share profile link',
    'profile.shareSubject': "{name}'s Catudy profile",
    'profile.shareText': '{name} shared a Catudy profile: {link}',
    'profile.shareCopied':
        'Sharing could not be opened, so the profile link was copied.',
    'profile.copyId': 'Copy my code',
    'profile.idCopied': 'User code copied.',
    'profile.myId': 'User code',
    'profile.editTitle': 'Edit Profile',
    'profile.chooseAvatar': 'Choose profile picture',
    'profile.uploadAvatar': 'Upload custom picture',
    'profile.saveProfile': 'Save profile',
    'profile.name': 'Name',
    'profile.publicTitle': 'Public Profile',
    'profile.publicBody':
        'The public view does not show private settings, token data, or sync metadata.',
    'profile.thisWeek': 'This week {minutes} min',
    'profile.favorite': 'Favorite: {category}',
    'profile.richStats': 'Profile summary',
    'profile.bestStreak': 'Best streak: {days}d',
    'profile.todayGoalShort': 'Today {done}/{goal} min',
    'profile.badges': 'Badges',
    'profile.noBadges': 'No unlocked badges yet.',
    'profile.publicStatsTitle': 'Profile stats',
    'profile.publicStatsHidden': 'This user keeps profile stats private.',
    'profile.sessionsPublic': '{count} sessions',
    'profile.totalPublic': 'Total {minutes} min',

    'settings.title': 'Settings',
    'settings.displayName': 'Display name',
    'settings.profileShareBaseUrl': 'Profile share address',
    'settings.profileShareBaseUrlHint': 'E.g. https://your-domain.com',
    'settings.privacy': 'Privacy',
    'settings.profileStatsVisibility': 'Show stats on profile',
    'settings.profileStatsVisibilityBody':
        'When off, profile visitors cannot see total time, streak, or sessions.',
    'settings.blockedUsers': 'Blocked users',
    'settings.noBlockedUsers': 'No blocked users.',
    'settings.unblock': 'Unblock',
    'settings.language': 'Language',
    'settings.turkish': 'Turkish',
    'settings.english': 'English',
    'settings.theme': 'Theme',
    'settings.system': 'System',
    'settings.light': 'Light',
    'settings.dark': 'Dark mode',
    'settings.dnd': 'Do not disturb reminder',
    'settings.petNotifications': 'Pet notifications',
    'settings.dailyGoalReminder': 'Daily target reminder',
    'settings.dailyGoalReminderBody': 'Remind every day at {time}.',
    'settings.changeReminderTime': 'Change reminder time',
    'settings.save': 'Save settings',
    'settings.saved': 'Settings saved',
    'settings.offline': 'Offline use is on. Data is kept on this device.',
    'settings.server': 'Sync is on.',
    'settings.authTitle': 'Account',
    'settings.authSignedIn': 'Signed in with {provider}: {email}',
    'settings.authSignedOut': 'Not signed in yet.',
    'settings.signOut': 'Sign out',
    'settings.openLogin': 'Open sign-in screen',
    'settings.demoWallet': 'Demo Wallet',
    'settings.demoWalletBody':
        'Tops gold up to 5000 and points up to 2500 for shop testing. Purchased items are kept.',
    'settings.demoWalletButton': 'Load demo wallet',
    'settings.demoWalletLoaded': 'Demo wallet loaded.',

    'lobby.title': 'Lobby',
    'lobby.chooseFlow': 'Choose whether to create a lobby or join one.',
    'lobby.createTitle': 'Create Lobby',
    'lobby.joinTitle': 'Join Lobby',
    'lobby.roomTitle': 'Lobby Room',
    'lobby.durationSetup': 'Choose focus duration or enter minutes manually.',
    'lobby.customMinutes': 'Minutes',
    'lobby.selectedDuration': 'Selected duration: {minutes} minutes',
    'lobby.noActiveLobby': 'No active lobby. Create one or join by code first.',
    'lobby.copyCode': 'Copy code',
    'lobby.codeCopied': 'Lobby code copied.',
    'lobby.shareInvite': 'Share lobby invite',
    'lobby.inviteText': 'Join my Catudy lobby. Code: {code}',
    'lobby.code': 'Join code: {code}',
    'lobby.onlineBackend': 'Online lobby is active. State syncs with Supabase.',
    'lobby.offlineBackend':
        'Supabase is not configured. Demo/offline lobby is being used for now.',
    'lobby.create': 'Create online lobby',
    'lobby.join': 'Join by code',
    'lobby.joinCode': 'Lobby code',
    'lobby.leave': 'Leave lobby',
    'lobby.enterCode': 'Enter a lobby code.',
    'lobby.demoMode':
        'No online config was found, so a demo lobby opened. Real lobbies need Supabase URL and anon key.',
    'lobby.onlyOwnerCanStart': 'Only the lobby owner can start the session.',
    'lobby.waitForSecondMember':
        'At least two people must be in the lobby to start.',
    'lobby.waitForReady': 'Everyone must be ready to start.',
    'lobby.owner': 'owner',
    'lobby.online': 'online',
    'lobby.offline': 'offline',
    'lobby.notReady': 'Not ready',
    'lobby.ready': 'Ready',
    'lobby.start': 'Start sync',
    'lobby.breakVote': 'Break vote',
    'lobby.breakVoteStatus': 'Yes: {yes}/{total} · No: {no}/{total}',
    'lobby.breakQuestion': 'Take a break? Votes sync with the lobby.',

    'tour.barrier': 'Catudy intro tour',
    'tour.homeTitle': 'This is the home screen',
    'tour.homeBody':
        "Track today's focus time, streak, reminders, and a short pet status here.",
    'tour.focusTitle': 'Focus starts here',
    'tour.focusBody':
        'Tap the clock button to choose a category and duration. Real sessions earn points, gold, and pet progress.',
    'tour.calendarTitle': 'Calendar',
    'tour.calendarBody':
        'Add manual records to past days, and create reminders with your own text for today or future days.',
    'tour.statsTitle': 'Stats',
    'tour.statsBody':
        'See your focus rhythm by week, month, and all time. Tap charts to open short explanations.',
    'tour.petTitle': 'Pet room',
    'tour.petBody':
        'Mochi lives here. Tap happiness, hunger, and energy bars to see what they mean.',
    'tour.profileTitle': 'Profile',
    'tour.profileBody':
        'Total focus, sessions, favorite category, equipped items, and your pet summary live here.',
    'onboarding.nameTitle': 'Let us know you',
    'onboarding.nameBody':
        'Choose the name shown on your profile and in lobbies. You can change it later.',
    'onboarding.petTitle': 'Choose your pet',
    'onboarding.petBody':
        'Mochi is your starting companion. New pets unlock as you earn points.',
    'onboarding.goalTitle': 'Daily target',
    'onboarding.goalBody': 'Set a realistic focus-minute target for today.',
    'onboarding.friendTitle': 'Friend code',
    'onboarding.friendBody': 'Friends use this code to add you.',
    'onboarding.startTitle': 'Ready for first focus',
    'onboarding.startBody':
        'Choose a category and duration to start your first focus session.',
    'onboarding.startFocus': 'Start first focus',
    'tour.skip': 'Skip',
    'tour.finish': 'Finish',
    'tour.next': 'Next',
  };
}
