class CatudyCopy {
  const CatudyCopy._();

  static String text(
    String languageCode,
    String key, [
    Map<String, Object?> values = const {},
  ]) {
    final source = languageCode == 'tr' ? _tr : _en;
    var value = source[key] ?? _en[key] ?? _tr[key] ?? key;
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return value;
  }

  static const _tr = <String, String>{
    'common.cancel': 'İptal',
    'common.close': 'Kapat',
    'common.complete': 'Tamamla',
    'common.continue': 'Devam et',
    'common.done': 'Tamam',
    'common.exit': 'Çık',
    'common.daysShort': 'g',
    'common.minutes': 'dakika',
    'common.minutesShort': 'dk',
    'common.no': 'Hayır',
    'common.save': 'Kaydet',
    'common.selected': 'Seçili',
    'common.select': 'Seç',
    'common.refresh': 'Yenile',
    'common.yes': 'Evet',
    'common.gold': 'coin',
    'common.hoursShort': 's',
    'common.points': 'puan',
    'common.delete': 'Sil',
    'common.clear': 'Temizle',
    'error.network':
        'Bağlantı kurulamadı. İnternetini kontrol edip tekrar dene.',
    'error.auth': 'Giriş bilgilerini kontrol edip tekrar dene.',
    'auth.genericError': 'Giriş işlemi tamamlanamadı. Biraz sonra tekrar dene.',
    'auth.deleteError': 'Hesap silinemedi. Biraz sonra tekrar dene.',
    'auth.deleteSetupError':
        'Sunucuda hesap silme fonksiyonu eksik. Supabase SQL kurulumunu çalıştırıp tekrar dene.',
    'auth.sessionExpired': 'Oturumun yenilenmeli. Tekrar giriş yapıp dene.',
    'lobby.genericError': 'Lobi işlemi tamamlanamadı. Biraz sonra tekrar dene.',
    'app.exitTitle': 'Uygulamadan çıkılsın mı?',
    'app.exitBody': 'Catudy kapatılacak. Emin misin?',
    'terms.title': 'Kullanıcı sözleşmesi',
    'terms.language': 'Sözleşme dili',
    'terms.intro':
        'Catudy’yi kullanarak aşağıdaki gizlilik ve kullanım şartlarını kabul etmiş olursun.',
    'terms.fullText': '''Gizlilik Özeti
Catudy; hesabını oluşturmak, odak seanslarını takip etmek, görevlerini/hatırlatmalarını göstermek, takvim kayıtlarını saklamak, pet ilerlemesini yürütmek, profilini paylaşmak ve lobi/sosyal özellikleri çalıştırmak için gerekli bilgileri işler.

Toplanabilecek veriler: görünen ad, e-posta veya giriş sağlayıcı bilgisi, profil tercihin, odak kayıtların, manuel takvim kayıtların, görevlerin, hatırlatmaların, pet/oda ilerlemen, mağaza-envanter seçimlerin, arkadaşlık/lobi verilerin, uygulama ayarların ve teknik hata kayıtları.

Konumunu, rehberini, fotoğraflarını veya diğer uygulamalarını izlemek için kullanmayız. Verilerini satmayız, reklam profili oluşturmak için kullanmayız ve kişisel üretkenlik verilerini iznin olmadan üçüncü kişilerle paylaşmayız.

Veriler cihazında saklanabilir ve hesabına giriş yaptığında senkronizasyon için güvenli bulut servislerine aktarılabilir. Aktarım sırasında şifreleme kullanılır. Hesabını veya yerel verilerini ayarlardan silebilirsin; sunucu tarafındaki kalıcı silme işlemleri için destek kanalları veya uygulama içi hesap silme akışı kullanılabilir.

Kullanım Şartları
Catudy; odaklanma, görev yönetimi, hatırlatma, istatistik, pet odası, kozmetik ödüller, profil paylaşımı, arkadaşlık ve lobi özellikleri sunan bir üretkenlik uygulamasıdır. Uygulama “olduğu gibi” sunulur; kesintisiz çalışacağı veya her ihtiyacını karşılayacağı garanti edilmez.

Catudy’yi kullanmak için en az 13 yaşında olmalısın. Hesap bilgilerini doğru tutmak, hesabını güvende tutmak ve kendi eklediğin içerikten sorumlu olmak sana aittir.

Yasaya aykırı kullanım, spam, taciz, başkası gibi davranma, hile, güvenlik önlemlerini aşma, tersine mühendislik, servisi bozma veya başkalarının haklarını ihlal eden içerik paylaşma yasaktır.

Uygulamanın tasarımı, markası, yazılımı ve görsel sistemi Catudy’ye aittir. Senin eklediğin görev, not, profil ve takvim içerikleri sana aittir; Catudy bu içerikleri yalnızca hizmeti sunmak ve senkronize etmek için işler.

Ücretsiz özellikler sunulabilir; Plus, sezon ödülleri, kozmetik kutular veya abonelikler gibi ücretli özellikler açık fiyat ve mağaza kurallarıyla çalışır. Abonelik iptali ve iade süreçleri ilgili uygulama mağazası kurallarına tabidir.

Şartlar veya gizlilik metni değişirse uygulama içinde veya uygun başka bir kanalla bilgilendirme yapılabilir. Önemli değişikliklerde tekrar onay istenebilir. Sorular için destek kanalından bizimle iletişime geçebilirsin.''',
    'terms.bulletAge':
        'Catudy 13 yaş ve üzeri kullanıcılar içindir; daha küçüksen ebeveyn izni gerekir.',
    'terms.bulletData':
        'Odak kayıtların, hedeflerin, profil adın ve sosyal/lobi verilerin uygulamayı çalıştırmak için saklanır.',
    'terms.bulletContent':
        'Eklediğin not ve profil içeriklerinden sen sorumlusun; başkalarının hakkını ihlal eden içerik ekleme.',
    'terms.bulletFairUse':
        'Hile, spam, taciz, tersine mühendislik veya yasa dışı kullanım yasaktır.',
    'terms.bulletDeletion':
        'Ayarlar bölümünden çıkış yapabilir ve yerel hesap verilerini silebilirsin.',
    'terms.acceptCheck':
        'Kullanıcı sözleşmesini ve gizlilik özetini kabul ediyorum.',
    'terms.accept': 'Kabul et',

    'auth.title': 'Giriş',
    'auth.subtitle': 'Catudy hesabına gir, lobileri ve ilerlemeyi eşitle.',
    'auth.displayName': 'Görünen ad',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.signIn': 'E-posta ile giriş',
    'auth.signUp': 'E-posta ile kayıt ol',
    'auth.haveAccount': 'Hesabım var',
    'auth.needAccount': 'Yeni hesap aç',
    'auth.google': 'Google ile devam et',
    'auth.apple': 'Apple ile devam et',
    'auth.guest': 'Misafir olarak devam et',
    'auth.displayNameRequired': 'Kayıt olmak için görünen ad gir.',
    'auth.offlineUnavailable':
        'Online giriş için Supabase bağlantısı gerekiyor.',

    'nav.home': 'Ana ekran',
    'nav.stats': 'İstatistik',
    'nav.calendar': 'Takvim',
    'nav.pet': 'Pet',
    'nav.social': 'Sosyal',
    'nav.profile': 'Profil',

    'home.greeting': 'İyi günler!',
    'home.petButton': 'Pet',
    'home.focusTime': 'Odak Zamanı',
    'home.heroStudyTitle': '{minutes} dakika çalış',
    'home.createLobby': 'Lobi Kur',
    'home.joinLobby': 'Lobiye Katıl',
    'home.todaySummary': 'Bugünün Özeti',
    'home.focus': 'Odak',
    'home.streak': 'Seri',
    'home.noSessions': 'Henüz kayıtlı seans yok',
    'home.lastSession': 'Son Seans: {minutes} dk',
    'home.todayReminders': 'Bugünkü Hatırlatmalar',
    'home.noTodayReminders': 'Bugün için hatırlatma yok.',
    'home.breakTitle': 'Kısa mola zamanı!',
    'home.breakBody': 'Biraz dinlen, sonra yeniden odaklan.',
    'home.happiness': 'Mutluluk',
    'home.hunger': 'Açlık',
    'home.good': 'İyi',
    'home.normal': 'Normal',
    'home.happy': 'Mutlu',
    'home.sad': 'Üzgün',
    'home.full': 'Tok',
    'home.hungry': 'Aç',
    'home.focusSuggestion': '{category} için {minutes} dakika çalışabilirsin.',
    'home.focusSuggestionReason':
        'Önceki {sessions} seansına göre bu ritim daha verimli görünüyor.',
    'home.focusSuggestionStarter':
        'İlk öneri için dengeli bir başlangıç süresi seçildi.',
    'home.prepareFocusPlan': 'Planı Hazırla',
    'home.adjustFocus': 'Ayarla',
    'home.unlockCoach': 'Koçu aç',
    'home.dailyGoal': 'Günlük hedef',
    'home.dailyGoalProgress': '{done}/{goal} dk tamamlandı. Kalan: {left} dk.',
    'home.dailyGoalRemaining': 'Kalan: {left} dk',
    'home.editDailyGoal': 'Günlük hedefi düzenle',
    'home.goalMinutes': 'Hedef dakika',
    'home.petWhisperTitle': '{pet} yanında',
    'home.petNextUnlock': '{pet} için {points} puan daha.',
    'home.petAllUnlocked': 'Tüm pet dostların açıldı.',
    'home.communityShortcut': 'Arkadaşlar ve birlikte çalışma',
    'home.rankingShortcut': 'Odak sıralamasını kontrol et',
    'home.collectionShortcut': '{count} başarı açıldı · koleksiyona bak',

    'achievements.title': 'Başarımlar',
    'celebration.achievementTitle': 'Başarım açıldı',
    'celebration.achievementBody': '{achievement} başarımı kazanıldı.',
    'celebration.dailyGoalTitle': 'Günlük hedef tamamlandı',
    'celebration.dailyGoalBody': '{minutes} dakikalık hedef bitti.',

    'social.title': 'Sosyal',
    'social.challengeProgress':
        '{done}/{goal} dk tamamlandı. Kalan {left} dk. Katılımcı: {people}',
    'social.friends': 'Arkadaşlar',
    'social.friendCount': 'Arkadaş',
    'social.participants': 'Katılımcı',
    'social.noFriends': 'Henüz arkadaş eklenmedi.',
    'social.addFriend': 'Arkadaş ekle',
    'social.sendFriendRequest': 'Arkadaşlık isteği gönder',
    'social.removeFriend': 'Arkadaştan çıkar',
    'social.visitProfile': 'Profili ziyaret et',
    'social.visitPetRoom': 'Pet odasını ziyaret et',
    'social.addByNameTitle': 'Kod ile arkadaş ekle',
    'social.friendSearchLabel': 'Kullanıcı kodu',
    'social.friendSearchHint': 'Örn. CAT-1A2B-9F8E',
    'social.requestButton': 'İstek gönder',
    'social.friendAdded': 'Arkadaş eklendi.',
    'social.friendRequestSent': 'Arkadaşlık isteği gönderildi.',
    'social.friendRequestPending': 'Bu kullanıcıyla bekleyen bir istek var.',
    'social.friendAlreadyAdded': 'Bu kullanıcı zaten arkadaş listende.',
    'social.friendSelf': 'Kendini arkadaş olarak ekleyemezsin.',
    'social.friendNotFound': 'Bu kullanıcı bulunamadı.',
    'social.friendBlocked': 'Bu kullanıcı engellenmiş.',
    'social.friendEmpty': 'Bir kullanıcı kodu gir.',
    'social.friendRequests': 'Arkadaşlık istekleri',
    'social.noFriendRequests': 'Bekleyen arkadaşlık isteği yok.',
    'social.incomingRequestFrom': '{name} arkadaşlık isteği gönderdi.',
    'social.outgoingRequestTo': '{name} için istek bekliyor.',
    'social.pending': 'Bekliyor',
    'social.cancelRequest': 'İsteği iptal et',
    'social.moreActions': 'Diğer işlemler',
    'social.removeFriendAction': 'Arkadaştan çıkar',
    'social.blockUser': 'Engelle',
    'social.reportUser': 'Şikayet et',
    'social.friendRemoved': 'Arkadaşlıktan çıkarıldı.',
    'social.requestCancelled': 'İstek iptal edildi.',
    'social.userBlocked': 'Kullanıcı engellendi.',
    'social.userReported': 'Şikayet kaydedildi.',
    'social.inviteToLobby': 'Davet et',
    'social.createLobbyFirst': 'Önce lobi kur. Seni lobi ekranına götürüyorum.',
    'social.lobbyInviteReady': 'Lobi daveti hazır.',

    'community.title': 'Topluluk',
    'community.friendsTab': 'Arkadaşlar',
    'community.rankingTab': 'Sıralama',
    'community.supportingBody': 'Birlikte ilerle, ama odağın merkezde kalsın.',
    'community.pendingRequests': '{count} bekleyen arkadaşlık isteği var.',

    'community.lobbiesTab': 'Lobiler',
    'community.lobbiesTitle': 'Birlikte odaklanma odaları',
    'community.lobbiesBody':
        'Arkadaşlarınla aynı ritme gir; süreyi seç, kodla katıl veya sakin bir lobi kur.',
    'community.lobbyComposerTitle': 'Lobi kur veya katıl',
    'community.lobbyComposerBody':
        'V1’de public keşif yok; güvenli akış kodla katılma ve mevcut lobidir.',
    'community.currentLobbyTitle': 'Aktif lobi',
    'community.noLobbyBody':
        'Henüz aktif lobi yok. Bir lobi kurabilir veya arkadaşından gelen kodla katılabilirsin.',

    'season.focusPassTitle': 'Focus Pass',
    'season.heroTitle': 'Monthly Focus Pass',
    'season.xpProgress': 'Season XP: {xp} / {target}',
    'season.daysLeft': 'Gün kaldı',
    'season.status': 'Durum',
    'season.unlockAtXp': '{xp} XP’de açılır',
    'season.premiumActiveBody':
        'Premium ödül yolu aktif; açılan ödülleri claim etmeyi unutma.',
    'season.upgradeTitle': 'Pass Yükselt',
    'season.upgradeBody':
        'Tüm premium ödülleri aç ve sezon koleksiyonunu tamamla.',
    'season.upgradeCta': 'Pass Yükselt',
    'season.dailyQuests': 'Günlük Görevler',
    'season.dailyQuestsBody':
        'Mevcut hedef ve hatırlatmalar sezon ritmini besler.',
    'season.questFocusTitle': 'Günlük odak hedefini ilerlet',
    'season.questReminderTitle': 'Bugünkü görevleri tamamla',
    'season.focusXp': 'Season XP',
    'season.daysShort': 'gün',
    'season.rewardsTitle': 'Focus Pass Ödülleri',
    'season.tapRewards': 'Ödülleri tam ekran gör',
    'season.reward.free_gold_60': '100 Coin',
    'season.reward.free_cat_crate_120': 'Kedi Kutusu',
    'season.reward.free_gold_180': '150 Coin',
    'season.reward.free_room_crate_300': 'Oda Kutusu',
    'season.reward.free_profile_badge_420': 'Profil Rozeti',
    'season.reward.free_style_crate_600': 'Stil Kutusu',
    'season.reward.free_gold_780': '250 Coin',
    'season.reward.free_room_crate_960': 'Oda Kutusu',
    'season.reward.free_cat_crate_1200': 'Kedi Kutusu',
    'season.reward.free_final_gold_1500': '400 Coin',
    'season.reward.plus_style_crate_60': 'Stil Kutusu',
    'season.reward.plus_season_cat_120': 'Sezon Kedi Kutusu',
    'season.reward.plus_gold_180': '250 Coin',
    'season.reward.plus_rainy_window_300': 'Yağmurlu Pencere',
    'season.reward.plus_season_room_420': 'Sezon Oda Kutusu',
    'season.reward.plus_dialogues_600': 'Masal Diyalogları',
    'season.reward.plus_profile_theme_780': 'Galaksi Profil Teması',
    'season.reward.plus_season_style_960': 'Sezon Stil Kutusu',
    'season.reward.plus_pet_widget_1200': 'Pet Widget Teması',
    'season.reward.plus_focus_crown_1500': 'Focus Crown Rozeti',

    'calendar.todayBadge': 'Bugün',
    'calendar.focusCompleted': '{minutes} dk odak tamamlandı',
    'calendar.rewardDay': 'Görev ödülü',
    'calendar.sessions': 'Seanslar',

    'stats.dashboardTitle': '{minutes} dk odaklandı',
    'stats.bestDayInsight': '{day} günü {minutes} dk ile öne çıktı.',
    'stats.sessionsDelta': '+8 geçen aya göre',
    'stats.averageDelta': '+6 dk geçen aya göre',
    'stats.bestDay': 'En iyi gün',
    'stats.focusTimeThisPeriod': 'Odak süresi',
    'stats.emptyMochiInsight':
        'Mochi veri topluyor; birkaç seans sonra ritmin daha görünür olacak.',
    'stats.mochiBestInsight': '{day} günleri odak süren yüksek görünüyor.',
    'stats.sessionsInfo': 'Bu aralıkta tamamlanan gerçek odak seansı: {count}.',
    'stats.averageSessionInfo': 'Seans başına ortalama süre: {minutes} dk.',
    'stats.bestDayInfo': '{day} günü {minutes} dk ile en güçlü gün.',
    'stats.bestDayInfoEmpty': 'Bu aralıkta henüz en iyi gün oluşmadı.',
    'stats.focusedTimeInfo': 'Bu aralıkta toplam {minutes} dk odak kaydı var.',
    'stats.categoryDistributionInfo':
        'Odak dakikalarının kategorilere dağılımı.',
    'stats.dayFocusInfo': 'Bu gün {minutes} dk odaklandı.',

    'profile.profileHeroBody': '{pet} senin en yakın odak dostun.',
    'profile.level': 'Lv. {level}',
    'profile.levelTitle': 'Seviye',
    'profile.interests': 'İlgi Alanları / Kategoriler',
    'profile.collection': 'Koleksiyon',
    'profile.monthlyTitle': 'Bu Ay',
    'profile.monthlyBody': '{minutes} dk / {target} dk ilerleme',
    'profile.friendsBody':
        '{count} arkadaşın var. Birlikte odaklanma lobilerini kontrol et.',

    'pet.level': 'Seviye',
    'pet.feed': 'Besle',
    'pet.play': 'Oyna',
    'pet.sleep': 'Uyu',
    'pet.love': 'Sev',
    'pet.rename': 'İsmi değiştir',

    'leaderboard.title': 'Leaderboard',
    'leaderboard.body':
        'Sıralama yalnızca gerçek odak dakikasına göre yapılır. Buradan profilleri ve pet odalarını ziyaret edebilirsin.',
    'leaderboard.focusTimeRanking': 'Odak Süresi Sıralaması',
    'leaderboard.overall': 'Genel',
    'leaderboard.realMinutesOnly': 'Yalnızca gerçek odak dakikaları sayılır.',
    'leaderboard.you': 'sen',
    'leaderboard.minutes': 'odak dk',
    'leaderboard.roomSoon': 'Pet odasını ziyaret et',
    'leaderboard.visitSoon': 'Pet odasını ziyaret et',
    'leaderboard.viewAll': 'Sonrasını görüntüle',

    'calendar.title': 'Takvim',
    'calendar.manualAdd': 'Kayıt Ekle',
    'calendar.reminderAdd': 'Hatırlatma',
    'calendar.reminders': 'Hatırlatmalar',
    'calendar.noReminders': 'Bugün için hatırlatma yok.',
    'calendar.records': 'Kayıtlar',
    'calendar.noRecords': 'Bugüne ait kayıt yok.',
    'calendar.pastInfo': 'Geçmiş gün: sadece manuel kayıt eklenebilir.',
    'calendar.todayInfo': 'Bugün: manuel kayıt ve hatırlatma eklenebilir.',
    'calendar.futureInfo': 'Gelecek gün: sadece hatırlatma eklenebilir.',
    'calendar.reminderTitle': 'Hatırlatma',
    'calendar.reminderText': 'Hatırlatma metni',
    'calendar.reminderHint': 'Örn. Matematik tekrarını bitir',
    'calendar.enterText': 'Metin gir.',
    'calendar.time': 'Saat: {time}',
    'calendar.batchSelected': '{count} gün seçildi',
    'calendar.batchHint':
        '{count} gün seçildi. Kayıt veya hatırlatma seçili günlere uygulanır.',
    'calendar.enterMinutes': 'Dakika gir.',
    'calendar.recordNote': 'Not',

    'manual.title': 'Manuel Kayıt',
    'manual.info': 'Manuel kayıtlar açıkça etiketlenir ve ödül kazandırmaz.',
    'manual.category': 'Kategori',
    'manual.minutes': 'Tamamlanan dakika',
    'manual.note': 'Not',
    'manual.save': 'Manuel kaydı kaydet',

    'stats.title': 'İstatistik',
    'stats.categoryDistribution': 'Kategori Dağılımı',
    'stats.noRecordsRange': 'Bu aralıkta kayıt yok.',
    'stats.focusGarden': 'Odak Bahçesi',
    'stats.focus': 'Odak',
    'stats.sessions': 'Seans',
    'stats.streak': 'Seri',
    'stats.week': 'Hafta',
    'stats.month': 'Ay',
    'stats.all': 'Tümü',
    'stats.total': 'toplam',
    'stats.manualNote':
        'Manuel kayıtlar raporda görünür, ancak coin ve leaderboard kredisi vermez.',
    'stats.insights': 'İçgörüler',
    'stats.averageSession': 'Ortalama seans',
    'stats.bestHour': 'En verimli saat',
    'stats.todayGoal': 'Bugünkü hedef',
    'stats.weeklyProgress': 'Haftalık ilerleme',
    'stats.monthlyProgress': 'Aylık ilerleme',
    'stats.allTimeProgress': 'Tüm zaman ilerlemesi',
    'stats.lastSevenDays': 'Son 7 gün',
    'stats.thisMonth': 'Bu ay',
    'stats.allRecords': 'Tüm kayıtlar',
    'stats.periodTotalMinutes': 'Toplam: {minutes} dk',
    'stats.plusLocked':
        'Ay ve tüm zaman görünümü, saat bazlı analizler ve koç içgörüleri Catudy Plus ile açılır.',
    'stats.openPlus': 'Plus',
    'stats.coachInsight': 'Koç İçgörüsü',

    'focus.categoryTitle': 'Kategori Seç',
    'focus.addCategoryClose': 'Kategori eklemeyi kapat',
    'focus.addCategoryOpen': 'Yeni kategori ekle',
    'focus.customCategory': 'Özel kategori',
    'focus.categoryName': 'Kategori adı',
    'focus.addCategory': 'Kategori ekle',
    'focus.tapSelect': 'Dokun ve seç',
    'focus.durationTitle': 'Süre Seç',
    'focus.durationInfo':
        'Odak süresini seç. Tamamlandığında ödül, pet durumu, istatistik ve takvim güncellenir.',
    'focus.customDuration': 'Özel süre',
    'focus.customMinutes': 'Dakika',
    'focus.selectedDuration': 'Seçili süre: {minutes} dakika',
    'focus.taskTitle': 'Odak görevi',
    'focus.noOpenTasks': 'Yaklaşan açık görev yok.',
    'focus.selectTask': 'Görev seç',
    'focus.noTaskSelected': 'Görevsiz odak',
    'focus.startComposerTitle': 'Odağı Başlat',
    'focus.readyTitle': 'Başlamaya hazır',
    'focus.readyBody': '{category} · {minutes} dk',
    'focus.showAdvanced': 'Daha fazla ayar',
    'focus.hideAdvanced': 'Ayarları gizle',
    'focus.startTimer': 'Timer başlat',
    'focus.start': 'Odak başlat',
    'focus.timerTitle': 'Odak Timer',
    'focus.lobbyTimerTitle': 'Lobi Timer',
    'focus.noActiveSession': 'Aktif seans yok. Yeni bir odak seansı başlat.',
    'focus.ritualBody': 'Mochi sessizce yanında; yalnızca bu seansa odaklan.',
    'focus.endFocus': 'Odağı Bitir',
    'focus.backHome': 'Ana menü',
    'focus.restoreInfo': 'Seans zaman damgasından geri yüklenir.',
    'focus.resultTitle': 'Seans Sonucu',
    'focus.resultEmpty': 'Henüz sonuç yok',
    'focus.resultComplete': 'Odak tamamlandı',
    'focus.resultEmptyBody': 'Ödül kazanmak için bir seans başlatıp tamamla.',
    'focus.resultSaved': '{category} için {minutes} dakika kaydedildi.',
    'focus.seeStats': 'İstatistikleri gör',
    'focus.openShop': 'Mağazayı aç',
    'focus.petUnlocked': 'Yeni pet açıldı',
    'focus.petUnlockedBody': '{pet} envantere eklendi.',
    'focus.resultSummary': 'Seans özeti',
    'focus.resultPointsEarned': 'Kazanılan puan',
    'focus.resultGoldEarned': 'Kazanılan coin',
    'focus.resultPetEffect': 'Pet etkisi',
    'focus.resultPetEffectValue': '+8 mutluluk',
    'focus.resultStreak': 'Seri durumu',
    'focus.resultStreakValue': '{days} gün seri',
    'focus.resultGoal': 'Günlük hedef',
    'focus.focusAgain': 'Tekrar odaklan',
    'focus.nextRewardTitle': 'Sıradaki ödül',
    'focus.nextRewardBody': '{pet} için {points} puan kaldı.',
    'focus.allPetsUnlocked': 'Tüm petler açıldı. Odanı süslemeye devam et.',

    'pet.room': 'Pet Odası',
    'pet.roomName': '{pet} Odası',
    'pet.roomSubtitle': 'Mochi burada dinlenir, bekler ve seninle çalışır.',
    'pet.noCosmetic': 'Takılı kozmetik yok',
    'pet.shop': 'Mağaza',
    'pet.inventory': 'Envanter',
    'pet.returnMyRoom': 'Kendi odama dön',
    'pet.showTour': 'Turu tekrar göster',
    'pet.settings': 'Ayarlar',
    'pet.mood': 'Mutluluk',
    'pet.energy': 'Enerji',
    'pet.roomBoost': 'Oda boostu',
    'pet.customizeTitle': 'Odayı düzenle',
    'pet.customizeBody': 'Sahip olduklarını tak, yenilerini mağazadan ekle.',
    'pet.roomMaintenanceTitle': 'Oda yenileniyor',
    'pet.roomMaintenanceBody':
        'Bu alan şu an inşaat halinde; bazı eşyalar yerinden oynayabilir.',
    'pet.nameDialogTitle': 'Petinin ismi ne olsun?',
    'pet.nameDialogBody':
        'İstersen önerilerden birini seçebilir ya da kendi ismini yazabilirsin.',
    'pet.nameField': 'Pet ismi',
    'pet.nameSave': 'İsmi kaydet',

    'shop.title': 'Mağaza',
    'shop.petUnlocks': 'Pet Kilitleri',
    'shop.roomFurniture': 'Oda Mobilyaları',
    'shop.cosmetics': 'Kozmetikler',
    'shop.rewardBoost': 'odak ödülü',
    'shop.owned': 'Alındı',
    'shop.buy': 'Al',
    'shop.openInventory': 'Envanteri aç',
    'shop.unlocked': 'Açık',
    'shop.cratesBody':
        'Kedi, oda ve stil kutularını aç; çıkan kozmetikler rekabet gücü değil, koleksiyon hissi verir.',
    'shop.openCrates': 'Kutular',
    'shop.plusCosmetics': 'Plus Kozmetikleri',
    'shop.plusOnly': 'Plus',
    'shop.category.room': 'Oda',
    'shop.category.pet': 'Pet',
    'shop.category.profile': 'Profil',
    'shop.category.extras': 'Ekstralar',
    'shop.category.crates': 'Kutular',
    'shop.section.roomBackgrounds': 'Oda temaları',
    'shop.noRoomBackgrounds': 'Şimdilik satılacak oda teması yok.',
    'shop.section.petItems': 'Pet aksesuarları',
    'shop.section.petStyles': 'Pet stilleri',
    'shop.section.profileItems': 'Profil aksesuarları',
    'shop.section.profileStyles': 'Profil stilleri',
    'shop.section.roomEffects': 'Oda efektleri',
    'shop.section.extras': 'Ekstra koleksiyon',
    'shop.room.slot.study': 'Çalışma köşesi',
    'shop.room.slot.bed': 'Uyku alanı',
    'shop.room.slot.decor': 'Işık ve dekor',
    'shop.room.slot.shelf': 'Raflar',

    'item.violet_collar.name': 'Mor Tasma',
    'item.violet_collar.description': 'Mochi için yumuşak bir pet kozmetiği.',
    'item.focus_badge.name': 'Odak Rozeti',
    'item.focus_badge.description': 'Herkese açık profilinde gösterilir.',
    'item.sunny_hat.name': 'Güneş Şapkası',
    'item.sunny_hat.description': 'Pet odası için sıcak bir kozmetik.',
    'item.soft_study_nook.name': 'Yumuşak Çalışma Alanı',
    'item.soft_study_nook.description':
        'Mochi için minderli, alçak bir çalışma köşesi.',
    'item.moonlit_study_nook.name': 'Ay Işıklı Çalışma Alanı',
    'item.moonlit_study_nook.description':
        'Odak seanslarında defter ve ışığıyla öne çıkan alan.',
    'item.cloud_nap_bed.name': 'Bulut Yatak',
    'item.cloud_nap_bed.description':
        'Odanın sağ köşesine yerleşen yumuşak uyku alanı.',
    'item.warm_den_bed.name': 'Sıcak Yuva Yatağı',
    'item.warm_den_bed.description':
        'Daha derin gölgeli, konforlu bir pet yatağı.',
    'item.glow_lantern.name': 'Parlayan Oda Lambası',
    'item.glow_lantern.description':
        'Odanın derinliğini güçlendiren küçük bir ışık.',
    'item.tiny_library_shelf.name': 'Mini Kitaplık',
    'item.tiny_library_shelf.description':
        'Çalışma alanının arkasına küçük kitap rafları ekler.',

    'inventory.title': 'Envanter',
    'inventory.ownedItems': 'Sahip olunanlar',
    'inventory.pets': 'Petler',
    'inventory.equipped': 'Tak',
    'inventory.roomEquipped': 'Odada yerinde',
    'inventory.roomFurniture': 'Oda mobilyası',
    'inventory.petEquipped': 'Pet üzerinde takılı',
    'inventory.petCosmetic': 'Pet kozmetiği',
    'inventory.profileEquipped': 'Profilde takılı',
    'inventory.profileCosmetic': 'Profil kozmetiği',
    'inventory.premiumCosmetics': 'Plus Kozmetikleri',
    'inventory.category.room': 'Oda',
    'inventory.category.pet': 'Pet',
    'inventory.category.profile': 'Profil',
    'inventory.category.extras': 'Ekstralar',
    'inventory.roomEffects': 'Oda efektleri',
    'inventory.petStyles': 'Pet stilleri',
    'inventory.profileStyles': 'Profil temaları',
    'inventory.profileBadges': 'Profil rozetleri',
    'inventory.widgetThemes': 'Widget temaları',
    'inventory.dialoguePacks': 'Diyalog paketleri',
    'inventory.emptyCategory': 'Bu kategoride henüz eşya yok.',
    'inventory.cosmeticSlot.pet_style': 'Pet stili',
    'inventory.cosmeticSlot.room_effect': 'Oda efekti',
    'inventory.cosmeticSlot.profile_theme': 'Profil teması',
    'inventory.cosmeticSlot.profile_badge': 'Profil rozeti',
    'inventory.cosmeticSlot.widget_theme': 'Widget teması',
    'inventory.cosmeticSlot.dialogue_pack': 'Diyalog paketi',

    'profile.title': 'Profil',
    'profile.subtitle': 'Odak meraklısı ve çalışma dostu',
    'profile.totalFocus': 'Toplam Odak',
    'profile.sessions': 'Seans',
    'profile.equippedItems': 'Takılı Eşyalar',
    'profile.noItems': 'Henüz eşya yok.',
    'profile.viewAll': 'Tümünü Gör',
    'profile.myPet': 'Petim',
    'profile.focusBuddy': 'Odak Dostu',
    'profile.petRoom': 'Pet Odası',
    'profile.favoriteCategory': 'Favori Kategori',
    'profile.weeklySummary': 'Haftalık Özet',
    'profile.dailyFocus': 'Günlük odak',
    'profile.edit': 'Profili Düzenle',
    'profile.share': 'Profil bağlantısını paylaş',
    'profile.shareSubject': '{name} Catudy profili',
    'profile.shareText': '{name} Catudy profil bağlantısını paylaştı: {link}',
    'profile.shareCopied':
        'Paylaşım açılamadı, profil bağlantısı panoya kopyalandı.',
    'profile.copyId': 'Kodumu kopyala',
    'profile.idCopied': 'Kullanıcı kodu kopyalandı.',
    'profile.myId': 'Kullanıcı kodu',
    'profile.editTitle': 'Profili Düzenle',
    'profile.chooseAvatar': 'Profil resmi seç',
    'profile.uploadAvatar': 'Özel resim yükle',
    'profile.saveProfile': 'Profili kaydet',
    'profile.name': 'İsim',
    'profile.publicTitle': 'Herkese Açık Profil',
    'profile.publicBody':
        'Herkese açık görünüm özel ayarları, token bilgisini ve sync metadatasını göstermez.',
    'profile.thisWeek': 'Bu hafta {minutes} dk',
    'profile.favorite': 'Favori: {category}',
    'profile.richStats': 'Profil özeti',
    'profile.bestStreak': 'En iyi seri: {days}g',
    'profile.todayGoalShort': 'Bugün {done}/{goal} dk',
    'profile.badges': 'Rozetler',
    'profile.noBadges': 'Henüz açılmış rozet yok.',
    'profile.publicStatsTitle': 'Profil istatistikleri',
    'profile.publicStatsHidden':
        'Bu kullanıcı profil istatistiklerini gizli tutuyor.',
    'profile.sessionsPublic': '{count} seans',
    'profile.totalPublic': 'Toplam {minutes} dk',
    'profile.plusActive': 'Catudy Plus aktif',
    'profile.plusLocked': 'Catudy Plus koleksiyonu',
    'profile.collectionSummary': '{count} premium kozmetik toplandı.',
    'profile.themeSummary': '{theme} aktif · {count} kozmetik toplandı.',
    'profile.openPlus': 'Aç',

    'premium.title': 'Catudy Plus',
    'premium.active': 'Catudy Plus aktif',
    'premium.pitch': 'Daha akıllı öneriler, daha zengin koleksiyon',
    'premium.heroTitle': 'Plus avantajları',
    'premium.heroHeadline': 'Daha fazla konfor.',
    'premium.heroAccent': 'Daha fazla purr-gress.',
    'premium.heroBody':
        'Daha sakin, daha zengin ve daha motive bir odak deneyimi.',
    'premium.whatYouGet': 'Neler var',
    'premium.benefitRoomsTitle': 'Özel oda temaları',
    'premium.benefitRoomsBody': 'Alanını Plus temalarla değiştir.',
    'premium.benefitPetTitle': 'Pet kostümleri',
    'premium.benefitPetBody': 'Mochi için özel görünümler.',
    'premium.benefitSeasonTitle': 'Sezon ödülleri',
    'premium.benefitSeasonBody': 'Bonus XP, coin ve kutular.',
    'premium.benefitStatsTitle': 'Gelişmiş içgörüler',
    'premium.benefitStatsBody': 'Daha derin odak analizi.',
    'premium.benefitSoundTitle': 'Ambient ses paketleri',
    'premium.benefitSoundBody': 'Daha sakin çalışma sesi.',
    'premium.benefitEarlyTitle': 'Erken erişim',
    'premium.benefitEarlyBody': 'Yeni özellikleri önce dene.',
    'premium.freeColumn': 'Free',
    'premium.plusColumn': 'Plus',
    'premium.compareRooms': 'Oda temaları',
    'premium.comparePet': 'Pet kozmetikleri',
    'premium.compareSeason': 'Sezon ödülleri',
    'premium.compareStats': 'Detaylı istatistik',
    'premium.compareBadges': 'Özel rozetler',
    'premium.compareAll': 'Tüm temalar',
    'premium.compareBasic': 'Temel',
    'premium.compareExclusive': 'Özel',
    'premium.compareAdvanced': 'Gelişmiş',
    'premium.monthly': 'Aylık',
    'premium.yearly': 'Yıllık',
    'premium.monthlyPrice': '\$4.99 / ay',
    'premium.yearlyPrice': '\$39.99 / yıl',
    'premium.bestValue': 'En iyi değer',
    'premium.trialCta': '7 günlük ücretsiz denemeyi başlat',
    'premium.cancelAnytime': 'İstediğin zaman iptal et. Taahhüt yok.',
    'premium.body':
        'Koç, gelişmiş istatistikler, sezon pass, premium kozmetikler, widget temaları ve Buddy Pass tek pakette.',
    'premium.featureCoach': 'Algoritmik koç',
    'premium.featureStats': 'Gelişmiş istatistik',
    'premium.featureSeason': 'Sezon pass',
    'premium.featureCosmetics': 'Premium kozmetik',
    'premium.activateDemo': 'Demo Plus aç',
    'premium.clearDemo': 'Demo Plus kapat',
    'premium.openSeason': 'Sezon Pass',
    'premium.openCrates': 'Kutular',
    'premium.widgetThemes': 'Widget / Lock-screen temaları',
    'premium.widgetClassic': 'Klasik widget',
    'premium.widgetPreview': '{done}/{goal} dk bugün',
    'premium.syncError': 'Plus durumu şu an senkronize edilemedi.',
    'premium.backendTitle': 'Plus senkron durumu',
    'premium.backendOnline': 'Online hesap bağlı; Plus sunucudan okunuyor.',
    'premium.backendOffline':
        'Online hesap bağlı değil; şu an yalnızca yerel demo durumu geçerli.',
    'premium.account': 'Hesap',
    'premium.notSignedIn': 'Giriş yapılmadı',
    'premium.status': 'Durum',
    'premium.statusActive': 'Aktif',
    'premium.statusInactive': 'Aktif değil',
    'premium.refresh': 'Plus durumunu yenile',

    'buddy.title': 'Buddy Pass',
    'buddy.body':
        'Her aktif Plus hesabı ayda 1 kez 30 günlük pass gönderebilir. Alıcı yeni kullanıcı olmak zorunda değildir; her hesap yalnızca 1 kez kullanabilir. Arkadaşın 180 gerçek odak dakikasına ulaşırsa Buddy Moon Pin rozeti kazanırsın.',
    'buddy.requirements':
        'Kullanmak için farklı, şu an Plus olmayan bir hesap gerekir.',
    'buddy.copy': 'Kopyala',
    'buddy.copied': 'Buddy Pass kodu kopyalandı.',
    'buddy.create': 'Buddy Pass oluştur',
    'buddy.created': 'Buddy Pass hazır.',
    'buddy.createFailed': 'Buddy Pass oluşturulamadı.',
    'buddy.monthlyUsed': 'Bu ayın Buddy Pass hakkı zaten kullanılmış.',
    'buddy.activePremiumRequired':
        'Buddy Pass göndermek için aktif Plus gerekiyor.',
    'buddy.authenticationRequired':
        'Buddy Pass için online hesaba giriş yapmalısın.',
    'buddy.redeemLabel': 'Buddy Pass kodu',
    'buddy.redeem': 'Kullan',
    'buddy.redeemed': 'Buddy Pass kullanıldı.',
    'buddy.invalid': 'Kod kullanılamadı.',

    'season.title': 'Focus Pass',
    'season.progress': '{minutes} gerçek odak dakikası',
    'season.freeTrack': 'Ücretsiz yol',
    'season.premiumTrack': 'Plus yolu',
    'season.unlockAt': '{minutes} dk’da açılır',
    'season.claim': 'Al',
    'season.claimed': 'Alındı',
    'season.previewTitle': 'Aylık sezon başladı',
    'season.previewBody': '{minutes} gerçek odak dakikası işlendi.',
    'season.open': 'Aç',

    'crates.title': 'Kutular',
    'crates.wallet': '{points} puan · {coin} coin · {shards} shard',
    'crates.collection': 'Koleksiyon',
    'crates.owned': '{count} adet',
    'crates.price': '{points} puan',
    'crates.plusOnly': 'Plus',
    'crates.buy': 'Al',
    'crates.open': 'Aç',
    'crates.opening': 'Kutu açılıyor',
    'crates.rolling': 'Ne çıkacak?',
    'crates.economyNote':
        'Kutular puanla alınır ve yalnızca kozmetik verir. Coin mağaza alışverişinde kalır; leaderboard’u gerçek odak dakikaları belirler.',

    'coach.starterHeadline': 'Güvenli başlangıç',
    'coach.starterReason':
        'Veri az olduğu için dengeli bir süre öneriyorum; birkaç gerçek seans sonra ritim kişiselleşecek.',
    'coach.historyHeadline': 'Son ritmine göre',
    'coach.bestHourHeadline': 'En güçlü penceren {hour}:00',
    'coach.shorterReason':
        '{category} seanslarında erken bitirme arttığı için {minutes} dakikalık daha temiz bir blok öneriyorum.',
    'coach.historyReason':
        'Son {sessions} {category} seansını harmanlayınca {minutes} dakika en dengeli seçenek görünüyor.',

    'settings.title': 'Ayarlar',
    'settings.displayName': 'Görünen ad',
    'settings.profileShareBaseUrl': 'Profil paylaşım adresi',
    'settings.profileShareBaseUrlHint': 'Örn. https://senin-domainin.com',
    'settings.privacy': 'Gizlilik',
    'settings.profileStatsVisibility': 'Profilde istatistikleri göster',
    'settings.profileStatsVisibilityBody':
        'Kapalıyken profilini ziyaret edenler toplam süre, seri ve seans bilgilerini görmez.',
    'settings.blockedUsers': 'Engellenen kullanıcılar',
    'settings.noBlockedUsers': 'Engellenen kullanıcı yok.',
    'settings.unblock': 'Engeli kaldır',
    'settings.language': 'Dil',
    'settings.turkish': 'Türkçe',
    'settings.english': 'English',
    'settings.theme': 'Tema',
    'settings.system': 'Sistem',
    'settings.light': 'Aydınlık',
    'settings.dark': 'Gece modu',
    'settings.dnd': 'Rahatsız etmeyin hatırlatıcısı',
    'settings.petNotifications': 'Pet bildirimleri',
    'settings.dailyGoalReminder': 'Günlük hedef hatırlatması',
    'settings.dailyGoalReminderBody': 'Her gün {time} saatinde hatırlat.',
    'settings.changeReminderTime': 'Hatırlatma saatini değiştir',
    'settings.monthlyGoal': 'Aylık hedef',
    'settings.monthlyGoalBody': 'Bu Ay hedefi.',
    'settings.save': 'Ayarları kaydet',
    'settings.saved': 'Ayarlar kaydedildi',
    'settings.offline':
        'Çevrim dışı kullanım açık. Veriler bu cihazda tutuluyor.',
    'settings.server': 'Senkronizasyon açık.',
    'settings.authTitle': 'Hesap',
    'settings.authSignedIn': '{provider} ile giriş yapıldı: {email}',
    'settings.authSignedOut': 'Henüz giriş yapılmadı.',
    'settings.signOut': 'Çıkış yap',
    'settings.openLogin': 'Giriş ekranını aç',
    'settings.deleteAccount': 'Hesabı sil',
    'settings.deleteAccountBody':
        'Bu işlem geri alınamaz. Hesabın, odak dakikaların, profilin, pet ilerlemen, görevlerin ve senkronize Catudy verilerin kalıcı olarak silinir.',
    'settings.deleteAccountConfirm': 'Hesabı sil',
    'settings.demoWallet': 'Demo Bakiyesi',
    'settings.demoWalletBody':
        'Mağaza denemeleri için coin’i 5000, puanı 2500 seviyesine tamamlar. Satın alınan eşyaları sıfırlamaz.',
    'settings.demoWalletButton': 'Demo bakiyesi yükle',
    'settings.demoWalletLoaded': 'Demo bakiyesi yüklendi.',

    'appLock.title': 'Uygulama Kilidi',
    'appLock.header': 'Odakla açılan kilitler',
    'appLock.headerBody':
        'Catudy, se\u{00E7}ti\u{011F}in uygulamalar\u{0131} odak tamamlanana kadar kapal\u{0131} tutar.',
    'appLock.masterSwitch': 'Uygulama kilidi aktif',
    'appLock.masterSwitchBody':
        'Kapalıyken Catudy kilit ekranı ve konum kuralları çalışmaz.',
    'appLock.permissions': 'İzinler',
    'appLock.permissionsBody':
        'Kilit ekran\u{0131}, uygulama takibi ve konum kurallar\u{0131} i\u{00E7}in gerekli izinleri kontrol eder.',
    'appLock.usageAccess': 'Kullanım erişimi',
    'appLock.overlayPermission': 'Üstte gösterme izni',
    'appLock.locationPermission': 'Konum izni',
    'appLock.backgroundLocationPermission': 'Arka plan konumu',
    'appLock.allowed': 'Açık',
    'appLock.open': 'Aç',
    'appLock.androidOnly': 'Bu cihazda uygulama kilidi desteklenmiyor.',
    'appLock.noInstalledApps': 'Uygulama listesi alınamadı.',
    'appLock.loadingApps': 'Uygulamalar yükleniyor...',
    'appLock.lockedApps': 'Kilitli uygulamalar',
    'appLock.addApp': 'Uygulama ekle',
    'appLock.noLockedApps': 'Henüz kilitli uygulama yok.',
    'appLock.searchApps': 'Uygulama ara',
    'appLock.requiredMinutes': '{minutes} dk odak',
    'appLock.unlockedToday': 'Bugün açık',
    'appLock.startFocus': 'Odak başlat',
    'appLock.limit': '{used}/{limit} ücretsiz limit',
    'appLock.plusUnlimited': 'Catudy Plus ile limitsiz',
    'appLock.plusLimit': 'Daha fazla uygulama için Catudy Plus',
    'appLock.limitReached': 'Ücretsiz limit doldu.',
    'appLock.locations': 'Konum kilitleri',
    'appLock.addLocation': 'Konum ekle',
    'appLock.noLocations': 'Henüz konum kilidi yok.',
    'appLock.locationLimit': '{used}/{limit} ücretsiz konum',
    'appLock.plusLocationLimit': 'Daha fazla konum için Catudy Plus',
    'appLock.locationLimitReached': 'Ücretsiz konum limiti doldu.',
    'appLock.strictLocation':
        'Se\u{00E7}ili konumdayken uygulamalar kapal\u{0131} kals\u{0131}n; konum kural\u{0131} kapan\u{0131}nca a\u{00E7}\u{0131}l\u{0131}r.',
    'appLock.locationDetails': '{radius} m yarıçap',
    'appLock.locationName': 'Konum adı',
    'appLock.searchLocation': 'Konum ara',
    'appLock.searchLocationHint': 'Adres, okul, kafe veya mahalle',
    'appLock.locationSearchNoResults': 'Eşleşen konum bulunamadı.',
    'appLock.locationSearchFailed': 'Konum araması şu an yapılamadı.',
    'appLock.useCurrentLocation': 'Konumum',
    'appLock.currentLocationUnavailable':
        'Konum alınamadı. İzinleri kontrol edip haritadan seçebilirsin.',
    'appLock.tapMapHint': 'Haritaya dokunarak konumu seç.',
    'appLock.selectedCoordinates': 'Seçili konum: {lat}, {lng}',
    'appLock.defaultLocationName': 'Odak alanı',
    'appLock.radiusMeters': 'Yarıçap: {radius} m',
    'appLock.saveLocation': 'Konumu kaydet',
    'settings.widgetSettingsTitle': 'Widget Ayarları',
    'settings.widgetSettingsBody':
        'Ana ekran widget\'larını ve kısayollarını yapılandırın.',
    'widget.previewTitle': 'Widget Görünümü',
    'widget.petLockLabel': 'Gösterilecek Evcil Hayvan',
    'widget.petLockFollowActive': 'Aktif evcil hayvanı takip et',
    'widget.shortcutCategoryLabel': 'Hızlı Odak Kategori',
    'widget.pinWidgetButton': 'Ana Ekrana Widget Ekle',
    'widget.pinWidgetSuccess': 'Widget ekleme isteği gönderildi!',
    'widget.pinWidgetFailed': 'Widget eklenemedi.',
    'widget.tabPet': 'Dostum',
    'widget.tabProgress': 'Hedef',
    'widget.tabShortcut': 'Kısayol',
    'widget.kind.pet': 'Pet',
    'widget.kind.goal': 'Hedef',
    'widget.kind.shortcut': 'Odak',
    'widget.kind.streak': 'Seri',
    'widget.kind.wallet': 'Cüzdan',
    'widget.configurations': 'Widget Özellikleri',
    'widget.petMood': 'Mod',
    'widget.petHunger': 'Açlık',
    'widget.petEnergy': 'Enerji',
    'widget.daysStreak': 'Gün Serisi',
    'widget.dailyGoalTitle': 'Günlük Hedef',
    'widget.goalCompleted': 'Hedef Tamamlandı! 🎉',
    'widget.completed': 'Tamamlandı',
    'widget.quickFocus': 'Hızlı Odak başlat',
    'widget.minLeft': 'dk kaldı',
    'widget.idle': 'Hazır',

    'lobby.title': 'Lobi',
    'lobby.chooseFlow':
        'Lobi kurmak veya mevcut bir lobiye katılmak için seçim yap.',
    'lobby.createTitle': 'Lobi Kur',
    'lobby.joinTitle': 'Lobiye Katıl',
    'lobby.roomTitle': 'Lobi Odası',
    'lobby.durationSetup': 'Odak süresini seç veya elle dakika gir.',
    'lobby.customMinutes': 'Dakika',
    'lobby.selectedDuration': 'Seçili süre: {minutes} dakika',
    'lobby.noActiveLobby': 'Aktif lobi yok. Önce lobi kur veya koda katıl.',
    'lobby.copyCode': 'Kodu kopyala',
    'lobby.codeCopied': 'Lobi kodu kopyalandı.',
    'lobby.shareInvite': 'Lobi daveti paylaş',
    'lobby.inviteText': 'Catudy lobime katıl. Kod: {code}',
    'lobby.code': 'Katılım kodu: {code}',
    'lobby.onlineBackend': 'Online lobi aktif. Durum Supabase ile eşitlenir.',
    'lobby.offlineBackend':
        'Supabase ayarı yok. Şimdilik demo/offline lobi kullanılıyor.',
    'lobby.create': 'Online lobi kur',
    'lobby.join': 'Koda katıl',
    'lobby.joinCode': 'Lobi kodu',
    'lobby.leave': 'Lobiden çık',
    'lobby.enterCode': 'Lobi kodu gir.',
    'lobby.demoMode':
        'Online ayar bulunamadığı için demo lobi açıldı. Gerçek lobi için Supabase URL ve anon key gerekiyor.',
    'lobby.onlyOwnerCanStart': 'Sadece lobi kurucusu seansı başlatabilir.',
    'lobby.waitForSecondMember': 'Başlatmak için lobide en az iki kişi olmalı.',
    'lobby.waitForReady': 'Başlatmak için herkes hazır olmalı.',
    'lobby.owner': 'kurucu',
    'lobby.online': 'çevrim içi',
    'lobby.offline': 'çevrim dışı',
    'lobby.notReady': 'Hazır değil',
    'lobby.ready': 'Hazır',
    'lobby.start': 'Senkron başlat',
    'lobby.breakVote': 'Mola oylaması',
    'lobby.breakVoteStatus': 'Evet: {yes}/{total} · Hayır: {no}/{total}',
    'lobby.breakQuestion': 'Molaya çıkılsın mı? Oylar lobiyle eşitlenir.',

    'tour.barrier': 'Catudy tanıtım turu',
    'tour.homeTitle': 'Burası ana ekran',
    'tour.homeBody':
        'Bugünün odak süresini, serini, hatırlatmalarını ve petinin kısa durumunu buradan takip edersin.',
    'tour.focusTitle': 'Odak burada başlar',
    'tour.focusBody':
        'Odak başlat düğmesine basınca kategori ve süre seçimine geçersin. Gerçek seanslar puan, coin ve pet gelişimi kazandırır.',
    'tour.calendarTitle': 'Takvim',
    'tour.calendarBody':
        'Takvim ekranında geçmiş günlere manuel kayıt ekleyebilir, bugün ve gelecek günler için kendi metninle hatırlatma oluşturabilirsin.',
    'tour.statsTitle': 'İstatistikler',
    'tour.statsBody':
        'Hafta, ay ve tüm zaman aralıklarında odak ritmini görürsün. Grafiklere dokununca kısa açıklamalar açılır.',
    'tour.petTitle': 'Pet odası',
    'tour.petBody':
        'Mochi burada yaşar. Mutluluk, açlık ve enerji barlarına dokunarak ne anlama geldiklerini görebilirsin.',
    'tour.profileTitle': 'Profil',
    'tour.profileBody':
        'Toplam odak, seans sayısı, favori kategori, takılı eşyalar ve pet özetin burada görünür.',
    'onboarding.nameTitle': 'Önce seni tanıyalım',
    'onboarding.nameBody':
        'Profilinde ve lobilerde görünecek adı seç. Bunu daha sonra profilden değiştirebilirsin.',
    'onboarding.petTitle': 'Petini seç',
    'onboarding.petBody':
        'Mochi başlangıç dostun. Puan kazandıkça yeni petlerin kilidi açılır.',
    'onboarding.goalTitle': 'Günlük hedef',
    'onboarding.goalBody':
        'Bugün için gerçekçi bir odak dakikası hedefi belirle.',
    'onboarding.friendTitle': 'Arkadaş kodu',
    'onboarding.friendBody': 'Arkadaşların seni eklemek için bu kodu kullanır.',
    'onboarding.startTitle': 'İlk odağa hazır',
    'onboarding.startBody':
        'Kategori ve süre seçerek ilk odak seansını başlatabilirsin.',
    'onboarding.startFocus': 'İlk odağı başlat',
    'tour.skip': 'Geç',
    'tour.finish': 'Bitir',
    'tour.next': 'Sonraki',
  };

  static const _en = <String, String>{
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.complete': 'Complete',
    'common.continue': 'Continue',
    'common.done': 'OK',
    'common.exit': 'Exit',
    'common.daysShort': 'd',
    'common.minutes': 'minutes',
    'common.minutesShort': 'min',
    'common.no': 'No',
    'common.save': 'Save',
    'common.selected': 'Selected',
    'common.select': 'Select',
    'common.refresh': 'Refresh',
    'common.yes': 'Yes',
    'common.gold': 'coin',
    'common.hoursShort': 'h',
    'common.points': 'points',
    'common.delete': 'Delete',
    'common.clear': 'Clear',
    'error.network': 'Could not connect. Check your internet and try again.',
    'error.auth': 'Check your sign-in details and try again.',
    'auth.genericError': 'Sign-in could not be completed. Try again shortly.',
    'auth.deleteError': 'Account could not be deleted. Try again shortly.',
    'auth.deleteSetupError':
        'The server account deletion function is missing. Run the Supabase SQL setup and try again.',
    'auth.sessionExpired':
        'Your session needs to be refreshed. Sign in again and try again.',
    'lobby.genericError':
        'Lobby action could not be completed. Try again shortly.',
    'app.exitTitle': 'Exit the app?',
    'app.exitBody': 'Catudy will close. Are you sure?',
    'terms.title': 'User agreement',
    'terms.language': 'Agreement language',
    'terms.intro':
        'By using Catudy, you accept this privacy and user agreement.',
    'terms.fullText': '''Privacy Summary
Catudy processes the information needed to create your account, track focus sessions, show tasks and reminders, store calendar records, run pet progress, share your profile, and support social/lobby features.

Data we may store includes display name, email or sign-in provider data, profile preferences, focus records, manual calendar records, tasks, reminders, pet and room progress, shop and inventory choices, friend/lobby data, app settings, and technical error logs.

We do not use your location, contacts, photos, or other apps for tracking. We do not sell your data, build advertising profiles, or share personal productivity data with other people without your permission.

Data may be stored on your device and, when you sign in, synced through secure cloud services. Transmission uses encryption. You can delete local data or your account from Settings; server-side permanent deletion may use the in-app account deletion flow or support channel.

Terms of Use
Catudy is a productivity app with focus tracking, task management, reminders, statistics, pet room, cosmetic rewards, profile sharing, friends, and lobby features. The app is provided as is; uninterrupted service or fitness for every specific need is not guaranteed.

You must be at least 13 years old to use Catudy. You are responsible for accurate account information, keeping your account secure, and the content you add.

Illegal use, spam, harassment, impersonation, cheating, bypassing security, reverse engineering, disrupting the service, or adding content that violates others rights is not allowed.

The Catudy app, design, brand, software, and visual system belong to Catudy. Tasks, notes, profile details, and calendar content you add remain yours; Catudy processes them only to provide and sync the service.

Free features may be offered. Paid features such as Plus, season rewards, cosmetic crates, or subscriptions use clear pricing and app-store rules. Subscription cancellation and refunds follow the relevant store policies.

If these terms or privacy rules change, we may notify you in the app or by another appropriate channel. Material changes may require acceptance again. For questions, contact support through the app.''',
    'terms.bulletAge':
        'Catudy is for users 13 and older; younger users need parent permission.',
    'terms.bulletData':
        'Your focus records, goals, profile name, and social/lobby data are stored to provide the app.',
    'terms.bulletContent':
        'You are responsible for notes and profile content you add; do not add content that violates others rights.',
    'terms.bulletFairUse':
        'Cheating, spam, harassment, reverse engineering, or illegal use is not allowed.',
    'terms.bulletDeletion':
        'You can sign out and delete local account data from Settings.',
    'terms.acceptCheck': 'I accept the user agreement and privacy summary.',
    'terms.accept': 'Accept',

    'auth.title': 'Sign in',
    'auth.subtitle': 'Sign in to Catudy and sync lobbies and progress.',
    'auth.displayName': 'Display name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign in with email',
    'auth.signUp': 'Sign up with email',
    'auth.haveAccount': 'I have an account',
    'auth.needAccount': 'Create account',
    'auth.google': 'Continue with Google',
    'auth.apple': 'Continue with Apple',
    'auth.guest': 'Continue as guest',
    'auth.displayNameRequired': 'Enter a display name to create an account.',
    'auth.offlineUnavailable':
        'Supabase connection is required for online auth.',

    'nav.home': 'Home',
    'nav.stats': 'Stats',
    'nav.calendar': 'Calendar',
    'nav.pet': 'Pet',
    'nav.social': 'Social',
    'nav.profile': 'Profile',

    'home.greeting': 'Have a good day!',
    'home.petButton': 'Pet',
    'home.focusTime': 'Focus Time',
    'home.heroStudyTitle': 'Study for {minutes} minutes',
    'home.createLobby': 'Create Lobby',
    'home.joinLobby': 'Join Lobby',
    'home.todaySummary': "Today's Summary",
    'home.focus': 'Focus',
    'home.streak': 'Streak',
    'home.noSessions': 'No sessions yet',
    'home.lastSession': 'Last Session: {minutes} min',
    'home.todayReminders': "Today's Reminders",
    'home.noTodayReminders': 'No reminders for today.',
    'home.breakTitle': 'Short break time!',
    'home.breakBody': 'Rest a little, then focus again.',
    'home.happiness': 'Happiness',
    'home.hunger': 'Hunger',
    'home.good': 'Good',
    'home.normal': 'Normal',
    'home.happy': 'Happy',
    'home.sad': 'Sad',
    'home.full': 'Full',
    'home.hungry': 'Hungry',
    'home.focusSuggestion': 'You can study {category} for {minutes} minutes.',
    'home.focusSuggestionReason':
        'Based on your last {sessions} sessions, this rhythm looks more efficient.',
    'home.focusSuggestionStarter':
        'A balanced starter duration was selected for the first recommendation.',
    'home.prepareFocusPlan': 'Prepare Plan',
    'home.adjustFocus': 'Adjust',
    'home.unlockCoach': 'Unlock coach',
    'home.dailyGoal': 'Daily target',
    'home.dailyGoalProgress':
        '{done}/{goal} min completed. Remaining: {left} min.',
    'home.dailyGoalRemaining': 'Remaining: {left} min',
    'home.editDailyGoal': 'Edit daily target',
    'home.goalMinutes': 'Target minutes',
    'home.petWhisperTitle': '{pet} is with you',
    'home.petNextUnlock': '{points} more points until {pet}.',
    'home.petAllUnlocked': 'All pet friends are unlocked.',
    'home.communityShortcut': 'Friends and shared sessions',
    'home.rankingShortcut': 'Check the focus ranking',
    'home.collectionShortcut':
        '{count} achievements unlocked · view collection',

    'achievements.title': 'Achievements',
    'celebration.achievementTitle': 'Achievement unlocked',
    'celebration.achievementBody': '{achievement} was unlocked.',
    'celebration.dailyGoalTitle': 'Daily target complete',
    'celebration.dailyGoalBody': 'Your {minutes}-minute target is done.',

    'social.title': 'Social',
    'social.challengeProgress':
        '{done}/{goal} min completed. {left} min left. People: {people}',
    'social.friends': 'Friends',
    'social.friendCount': 'Friends',
    'social.participants': 'Participants',
    'social.noFriends': 'No friends added yet.',
    'social.addFriend': 'Add friend',
    'social.sendFriendRequest': 'Send friend request',
    'social.removeFriend': 'Remove friend',
    'social.visitProfile': 'Visit profile',
    'social.visitPetRoom': 'Visit pet room',
    'social.addByNameTitle': 'Add friend by code',
    'social.friendSearchLabel': 'User code',
    'social.friendSearchHint': 'E.g. CAT-1A2B-9F8E',
    'social.requestButton': 'Send request',
    'social.friendAdded': 'Friend added.',
    'social.friendRequestSent': 'Friend request sent.',
    'social.friendRequestPending':
        'There is already a pending request with this user.',
    'social.friendAlreadyAdded': 'This user is already in your friends list.',
    'social.friendSelf': 'You cannot add yourself as a friend.',
    'social.friendNotFound': 'User not found.',
    'social.friendBlocked': 'This user is blocked.',
    'social.friendEmpty': 'Enter a user code.',
    'social.friendRequests': 'Friend requests',
    'social.noFriendRequests': 'No pending friend requests.',
    'social.incomingRequestFrom': '{name} sent a friend request.',
    'social.outgoingRequestTo': 'Request pending for {name}.',
    'social.pending': 'Pending',
    'social.cancelRequest': 'Cancel request',
    'social.moreActions': 'More actions',
    'social.removeFriendAction': 'Remove friend',
    'social.blockUser': 'Block',
    'social.reportUser': 'Report',
    'social.friendRemoved': 'Friend removed.',
    'social.requestCancelled': 'Request cancelled.',
    'social.userBlocked': 'User blocked.',
    'social.userReported': 'Report saved.',
    'social.inviteToLobby': 'Invite',
    'social.createLobbyFirst':
        'Create a lobby first. Taking you to the lobby screen.',
    'social.lobbyInviteReady': 'Lobby invite is ready.',

    'community.title': 'Community',
    'community.friendsTab': 'Friends',
    'community.rankingTab': 'Ranking',
    'community.supportingBody': 'Progress together without losing the focus.',
    'community.pendingRequests': '{count} pending friend requests.',

    'community.lobbiesTab': 'Lobbies',
    'community.lobbiesTitle': 'Focus rooms with friends',
    'community.lobbiesBody':
        'Enter the same rhythm with friends; pick a duration, join by code, or create a calm lobby.',
    'community.lobbyComposerTitle': 'Create or join a lobby',
    'community.lobbyComposerBody':
        'V1 has no public discovery; the safe flow is code join and current lobby state.',
    'community.currentLobbyTitle': 'Active lobby',
    'community.noLobbyBody':
        'No active lobby yet. Create one or join with a code from a friend.',

    'season.focusPassTitle': 'Focus Pass',
    'season.heroTitle': 'Monthly Focus Pass',
    'season.xpProgress': 'Season XP: {xp} / {target}',
    'season.daysLeft': 'Days left',
    'season.status': 'Status',
    'season.unlockAtXp': 'Unlocks at {xp} XP',
    'season.premiumActiveBody':
        'Premium reward track is active; remember to claim unlocked rewards.',
    'season.upgradeTitle': 'Upgrade Pass',
    'season.upgradeBody':
        'Unlock every premium reward and complete the season collection.',
    'season.upgradeCta': 'Upgrade Pass',
    'season.dailyQuests': 'Daily Quests',
    'season.dailyQuestsBody':
        'Your current target and reminders feed the season rhythm.',
    'season.questFocusTitle': "Progress today's focus target",
    'season.questReminderTitle': "Complete today's tasks",
    'season.focusXp': 'Season XP',
    'season.daysShort': 'days',
    'season.rewardsTitle': 'Focus Pass Rewards',
    'season.tapRewards': 'Open rewards full screen',
    'season.reward.free_gold_60': '100 Coin',
    'season.reward.free_cat_crate_120': 'Cat Crate',
    'season.reward.free_gold_180': '150 Coin',
    'season.reward.free_room_crate_300': 'Room Crate',
    'season.reward.free_profile_badge_420': 'Profile Badge',
    'season.reward.free_style_crate_600': 'Style Crate',
    'season.reward.free_gold_780': '250 Coin',
    'season.reward.free_room_crate_960': 'Room Crate',
    'season.reward.free_cat_crate_1200': 'Cat Crate',
    'season.reward.free_final_gold_1500': '400 Coin',
    'season.reward.plus_style_crate_60': 'Style Crate',
    'season.reward.plus_season_cat_120': 'Season Cat Crate',
    'season.reward.plus_gold_180': '250 Coin',
    'season.reward.plus_rainy_window_300': 'Rainy Window',
    'season.reward.plus_season_room_420': 'Season Room Crate',
    'season.reward.plus_dialogues_600': 'Storybook Dialogues',
    'season.reward.plus_profile_theme_780': 'Galaxy Profile Theme',
    'season.reward.plus_season_style_960': 'Season Style Crate',
    'season.reward.plus_pet_widget_1200': 'Pet Widget Theme',
    'season.reward.plus_focus_crown_1500': 'Focus Crown Badge',

    'calendar.todayBadge': 'Today',
    'calendar.focusCompleted': '{minutes} min focus completed',
    'calendar.rewardDay': 'Quest reward',
    'calendar.sessions': 'Sessions',

    'stats.dashboardTitle': '{minutes} min focused',
    'stats.bestDayInsight': '{day} stands out with {minutes} min.',
    'stats.sessionsDelta': '+8 vs last month',
    'stats.averageDelta': '+6 min vs last month',
    'stats.bestDay': 'Best day',
    'stats.focusTimeThisPeriod': 'Focused time',
    'stats.emptyMochiInsight':
        'Mochi is gathering data; your rhythm will become clearer after a few sessions.',
    'stats.mochiBestInsight': 'Your focus time looks strong on {day}.',
    'stats.sessionsInfo':
        'Real focus sessions completed in this range: {count}.',
    'stats.averageSessionInfo': 'Average length per session: {minutes} min.',
    'stats.bestDayInfo': '{day} is strongest with {minutes} min.',
    'stats.bestDayInfoEmpty': 'No best day yet in this range.',
    'stats.focusedTimeInfo':
        'Total focus recorded in this range: {minutes} min.',
    'stats.categoryDistributionInfo':
        'How your focus minutes split by category.',
    'stats.dayFocusInfo': 'Focused {minutes} min on this day.',

    'profile.profileHeroBody': '{pet} is your closest focus buddy.',
    'profile.level': 'Lv. {level}',
    'profile.levelTitle': 'Level',
    'profile.interests': 'Interests / Categories',
    'profile.collection': 'Collection',
    'profile.monthlyTitle': 'This Month',
    'profile.monthlyBody': '{minutes} min / {target} min progress',
    'profile.friendsBody':
        'You have {count} friends. Check shared focus lobbies.',

    'pet.level': 'Level',
    'pet.feed': 'Feed',
    'pet.play': 'Play',
    'pet.sleep': 'Sleep',
    'pet.love': 'Love',
    'pet.rename': 'Rename',

    'leaderboard.title': 'Leaderboard',
    'leaderboard.body':
        'Ranking uses only real focus minutes. You can visit profiles and pet rooms from here.',
    'leaderboard.focusTimeRanking': 'Focus Time Ranking',
    'leaderboard.overall': 'Overall',
    'leaderboard.realMinutesOnly': 'Only real focus minutes count.',
    'leaderboard.you': 'you',
    'leaderboard.minutes': 'focus min',
    'leaderboard.roomSoon': 'Visit pet room',
    'leaderboard.visitSoon': 'Visit pet room',
    'leaderboard.viewAll': 'View the rest',

    'calendar.title': 'Calendar',
    'calendar.manualAdd': 'Add Record',
    'calendar.reminderAdd': 'Reminder',
    'calendar.reminders': 'Reminders',
    'calendar.noReminders': 'No reminders for this day.',
    'calendar.records': 'Records',
    'calendar.noRecords': 'No records for this day.',
    'calendar.pastInfo': 'Past day: only manual records can be added.',
    'calendar.todayInfo': 'Today: manual records and reminders can be added.',
    'calendar.futureInfo': 'Future day: only reminders can be added.',
    'calendar.reminderTitle': 'Reminder',
    'calendar.reminderText': 'Reminder text',
    'calendar.reminderHint': 'E.g. finish math review',
    'calendar.enterText': 'Enter text.',
    'calendar.time': 'Time: {time}',
    'calendar.batchSelected': '{count} days selected',
    'calendar.batchHint':
        '{count} days selected. A record or reminder applies to selected days.',
    'calendar.enterMinutes': 'Enter minutes.',
    'calendar.recordNote': 'Note',

    'manual.title': 'Manual Record',
    'manual.info':
        'Manual records are clearly labeled and do not give rewards.',
    'manual.category': 'Category',
    'manual.minutes': 'Completed minutes',
    'manual.note': 'Note',
    'manual.save': 'Save manual record',

    'stats.title': 'Stats',
    'stats.categoryDistribution': 'Category Distribution',
    'stats.noRecordsRange': 'No records in this range.',
    'stats.focusGarden': 'Focus Garden',
    'stats.focus': 'Focus',
    'stats.sessions': 'Sessions',
    'stats.streak': 'Streak',
    'stats.week': 'Week',
    'stats.month': 'Month',
    'stats.all': 'All',
    'stats.total': 'total',
    'stats.manualNote':
        'Manual records appear in reports, but do not give coin or leaderboard credit.',
    'stats.insights': 'Insights',
    'stats.averageSession': 'Average session',
    'stats.bestHour': 'Best hour',
    'stats.todayGoal': "Today's target",
    'stats.weeklyProgress': 'Weekly progress',
    'stats.monthlyProgress': 'Monthly progress',
    'stats.allTimeProgress': 'All-time progress',
    'stats.lastSevenDays': 'Last 7 days',
    'stats.thisMonth': 'This month',
    'stats.allRecords': 'All records',
    'stats.periodTotalMinutes': 'Total: {minutes} min',
    'stats.plusLocked':
        'Month and all-time views, hourly analysis, and coach insights unlock with Catudy Plus.',
    'stats.openPlus': 'Plus',
    'stats.coachInsight': 'Coach Insight',

    'focus.categoryTitle': 'Choose Category',
    'focus.addCategoryClose': 'Close category form',
    'focus.addCategoryOpen': 'Add new category',
    'focus.customCategory': 'Custom category',
    'focus.categoryName': 'Category name',
    'focus.addCategory': 'Add category',
    'focus.tapSelect': 'Tap to select',
    'focus.durationTitle': 'Choose Duration',
    'focus.durationInfo':
        'Choose focus duration. Rewards, pet state, stats, and calendar update when it is complete.',
    'focus.customDuration': 'Custom duration',
    'focus.customMinutes': 'Minutes',
    'focus.selectedDuration': 'Selected duration: {minutes} minutes',
    'focus.taskTitle': 'Focus task',
    'focus.noOpenTasks': 'No upcoming open tasks.',
    'focus.selectTask': 'Select task',
    'focus.noTaskSelected': 'Focus without a task',
    'focus.startComposerTitle': 'Start Focus',
    'focus.readyTitle': 'Ready to begin',
    'focus.readyBody': '{category} · {minutes} min',
    'focus.showAdvanced': 'More settings',
    'focus.hideAdvanced': 'Hide settings',
    'focus.startTimer': 'Start timer',
    'focus.start': 'Start focus',
    'focus.timerTitle': 'Focus Timer',
    'focus.lobbyTimerTitle': 'Lobby Timer',
    'focus.noActiveSession': 'No active session. Start a new focus session.',
    'focus.ritualBody': 'Mochi is beside you; only this session matters now.',
    'focus.endFocus': 'End Focus',
    'focus.backHome': 'Home',
    'focus.restoreInfo': 'Session restores from its timestamp.',
    'focus.resultTitle': 'Session Result',
    'focus.resultEmpty': 'No result yet',
    'focus.resultComplete': 'Focus complete',
    'focus.resultEmptyBody': 'Start and complete a session to earn rewards.',
    'focus.resultSaved': '{minutes} minutes saved for {category}.',
    'focus.seeStats': 'See stats',
    'focus.openShop': 'Open shop',
    'focus.petUnlocked': 'New pet unlocked',
    'focus.petUnlockedBody': '{pet} was added to inventory.',
    'focus.resultSummary': 'Session summary',
    'focus.resultPointsEarned': 'Points earned',
    'focus.resultGoldEarned': 'Coin earned',
    'focus.resultPetEffect': 'Pet effect',
    'focus.resultPetEffectValue': '+8 happiness',
    'focus.resultStreak': 'Streak status',
    'focus.resultStreakValue': '{days} day streak',
    'focus.resultGoal': 'Daily target',
    'focus.focusAgain': 'Focus again',
    'focus.nextRewardTitle': 'Next reward',
    'focus.nextRewardBody': '{points} points left until {pet}.',
    'focus.allPetsUnlocked': 'All pets are unlocked. Keep styling the room.',

    'pet.room': 'Pet Room',
    'pet.roomName': "{pet}'s Room",
    'pet.roomSubtitle': 'Mochi rests, waits, and studies with you here.',
    'pet.noCosmetic': 'No cosmetic equipped',
    'pet.shop': 'Shop',
    'pet.inventory': 'Inventory',
    'pet.returnMyRoom': 'Return to my room',
    'pet.showTour': 'Show tour again',
    'pet.settings': 'Settings',
    'pet.mood': 'Happiness',
    'pet.energy': 'Energy',
    'pet.roomBoost': 'Room boost',
    'pet.customizeTitle': 'Style the room',
    'pet.customizeBody': 'Equip what you own or add new pieces from the shop.',
    'pet.roomMaintenanceTitle': 'Room refresh in progress',
    'pet.roomMaintenanceBody':
        'This room is under construction, so a few details may shift for now.',
    'pet.nameDialogTitle': 'What should your pet be called?',
    'pet.nameDialogBody': 'Pick a suggestion or type your own pet name.',
    'pet.nameField': 'Pet name',
    'pet.nameSave': 'Save name',

    'shop.title': 'Shop',
    'shop.petUnlocks': 'Pet Unlocks',
    'shop.roomFurniture': 'Room Furniture',
    'shop.cosmetics': 'Cosmetics',
    'shop.rewardBoost': 'focus reward',
    'shop.owned': 'Owned',
    'shop.buy': 'Buy',
    'shop.openInventory': 'Open inventory',
    'shop.unlocked': 'Unlocked',
    'shop.cratesBody':
        'Open cat, room, and style crates; every reward is cosmetic, never competitive power.',
    'shop.openCrates': 'Crates',
    'shop.plusCosmetics': 'Plus Cosmetics',
    'shop.plusOnly': 'Plus',
    'shop.category.room': 'Room',
    'shop.category.pet': 'Pet',
    'shop.category.profile': 'Profile',
    'shop.category.extras': 'Extras',
    'shop.category.crates': 'Crates',
    'shop.section.roomBackgrounds': 'Room themes',
    'shop.noRoomBackgrounds': 'No room themes are available yet.',
    'shop.section.petItems': 'Pet accessories',
    'shop.section.petStyles': 'Pet styles',
    'shop.section.profileItems': 'Profile accessories',
    'shop.section.profileStyles': 'Profile styles',
    'shop.section.roomEffects': 'Room effects',
    'shop.section.extras': 'Extra collection',
    'shop.room.slot.study': 'Study corner',
    'shop.room.slot.bed': 'Sleep corner',
    'shop.room.slot.decor': 'Lighting & decor',
    'shop.room.slot.shelf': 'Shelves',

    'item.violet_collar.name': 'Violet Collar',
    'item.violet_collar.description': 'A soft pet cosmetic for Mochi.',
    'item.focus_badge.name': 'Focus Badge',
    'item.focus_badge.description': 'Shown on your public profile.',
    'item.sunny_hat.name': 'Sunny Hat',
    'item.sunny_hat.description': 'A warm cosmetic for Pet Room.',
    'item.soft_study_nook.name': 'Soft Study Nook',
    'item.soft_study_nook.description':
        'A cushioned low study corner made for Mochi.',
    'item.moonlit_study_nook.name': 'Moonlit Study Nook',
    'item.moonlit_study_nook.description':
        'A notebook and moon lamp setup for focus sessions.',
    'item.cloud_nap_bed.name': 'Cloud Nap Bed',
    'item.cloud_nap_bed.description':
        'A soft sleeping spot placed in the right corner.',
    'item.warm_den_bed.name': 'Warm Den Bed',
    'item.warm_den_bed.description':
        'A cozier pet bed with deeper shadows and padding.',
    'item.glow_lantern.name': 'Glow Lantern',
    'item.glow_lantern.description':
        'A small light that makes the room feel deeper.',
    'item.tiny_library_shelf.name': 'Tiny Library Shelf',
    'item.tiny_library_shelf.description':
        'Adds compact book shelves behind the study area.',

    'inventory.title': 'Inventory',
    'inventory.ownedItems': 'Owned items',
    'inventory.pets': 'Pets',
    'inventory.equipped': 'Equip',
    'inventory.roomEquipped': 'Placed in room',
    'inventory.roomFurniture': 'Room furniture',
    'inventory.petEquipped': 'Equipped on pet',
    'inventory.petCosmetic': 'Pet cosmetic',
    'inventory.profileEquipped': 'Equipped on profile',
    'inventory.profileCosmetic': 'Profile cosmetic',
    'inventory.premiumCosmetics': 'Plus Cosmetics',
    'inventory.category.room': 'Room',
    'inventory.category.pet': 'Pet',
    'inventory.category.profile': 'Profile',
    'inventory.category.extras': 'Extras',
    'inventory.roomEffects': 'Room effects',
    'inventory.petStyles': 'Pet styles',
    'inventory.profileStyles': 'Profile themes',
    'inventory.profileBadges': 'Profile badges',
    'inventory.widgetThemes': 'Widget themes',
    'inventory.dialoguePacks': 'Dialogue packs',
    'inventory.emptyCategory': 'No items in this category yet.',
    'inventory.cosmeticSlot.pet_style': 'Pet style',
    'inventory.cosmeticSlot.room_effect': 'Room effect',
    'inventory.cosmeticSlot.profile_theme': 'Profile theme',
    'inventory.cosmeticSlot.profile_badge': 'Profile badge',
    'inventory.cosmeticSlot.widget_theme': 'Widget theme',
    'inventory.cosmeticSlot.dialogue_pack': 'Dialogue pack',

    'profile.title': 'Profile',
    'profile.subtitle': 'Focus enthusiast and study buddy',
    'profile.totalFocus': 'Total Focus',
    'profile.sessions': 'Sessions',
    'profile.equippedItems': 'Equipped Items',
    'profile.noItems': 'No items yet.',
    'profile.viewAll': 'View All',
    'profile.myPet': 'My Pet',
    'profile.focusBuddy': 'Focus Buddy',
    'profile.petRoom': 'Pet Room',
    'profile.favoriteCategory': 'Favorite Category',
    'profile.weeklySummary': 'Weekly Summary',
    'profile.dailyFocus': 'Daily focus',
    'profile.edit': 'Edit Profile',
    'profile.share': 'Share profile link',
    'profile.shareSubject': "{name}'s Catudy profile",
    'profile.shareText': '{name} shared a Catudy profile: {link}',
    'profile.shareCopied':
        'Sharing could not be opened, so the profile link was copied.',
    'profile.copyId': 'Copy my code',
    'profile.idCopied': 'User code copied.',
    'profile.myId': 'User code',
    'profile.editTitle': 'Edit Profile',
    'profile.chooseAvatar': 'Choose profile picture',
    'profile.uploadAvatar': 'Upload custom picture',
    'profile.saveProfile': 'Save profile',
    'profile.name': 'Name',
    'profile.publicTitle': 'Public Profile',
    'profile.publicBody':
        'The public view does not show private settings, token data, or sync metadata.',
    'profile.thisWeek': 'This week {minutes} min',
    'profile.favorite': 'Favorite: {category}',
    'profile.richStats': 'Profile summary',
    'profile.bestStreak': 'Best streak: {days}d',
    'profile.todayGoalShort': 'Today {done}/{goal} min',
    'profile.badges': 'Badges',
    'profile.noBadges': 'No unlocked badges yet.',
    'profile.publicStatsTitle': 'Profile stats',
    'profile.publicStatsHidden': 'This user keeps profile stats private.',
    'profile.sessionsPublic': '{count} sessions',
    'profile.totalPublic': 'Total {minutes} min',
    'profile.plusActive': 'Catudy Plus active',
    'profile.plusLocked': 'Catudy Plus collection',
    'profile.collectionSummary': '{count} premium cosmetics collected.',
    'profile.themeSummary': '{theme} active · {count} cosmetics collected.',
    'profile.openPlus': 'Open',

    'premium.title': 'Catudy Plus',
    'premium.active': 'Catudy Plus active',
    'premium.pitch': 'Smarter guidance, richer collection',
    'premium.heroTitle': 'Plus benefits',
    'premium.heroHeadline': 'More perks.',
    'premium.heroAccent': 'More purr-gress.',
    'premium.heroBody': 'A calmer, richer, more motivating focus experience.',
    'premium.whatYouGet': 'What you get',
    'premium.benefitRoomsTitle': 'Exclusive room themes',
    'premium.benefitRoomsBody': 'Decorate with Plus themes.',
    'premium.benefitPetTitle': 'Premium pet outfits',
    'premium.benefitPetBody': 'Special looks for Mochi.',
    'premium.benefitSeasonTitle': 'Season rewards',
    'premium.benefitSeasonBody': 'Bonus XP, coins, and crates.',
    'premium.benefitStatsTitle': 'Advanced insights',
    'premium.benefitStatsBody': 'Deeper focus analysis.',
    'premium.benefitSoundTitle': 'Ambient sound packs',
    'premium.benefitSoundBody': 'Calmer study audio.',
    'premium.benefitEarlyTitle': 'Early access',
    'premium.benefitEarlyBody': 'Try new features first.',
    'premium.freeColumn': 'Free',
    'premium.plusColumn': 'Plus',
    'premium.compareRooms': 'Room themes',
    'premium.comparePet': 'Pet cosmetics',
    'premium.compareSeason': 'Season rewards',
    'premium.compareStats': 'Detailed stats',
    'premium.compareBadges': 'Special badges',
    'premium.compareAll': 'All themes',
    'premium.compareBasic': 'Basic',
    'premium.compareExclusive': 'Exclusive',
    'premium.compareAdvanced': 'Advanced',
    'premium.monthly': 'Monthly',
    'premium.yearly': 'Yearly',
    'premium.monthlyPrice': '\$4.99 / month',
    'premium.yearlyPrice': '\$39.99 / year',
    'premium.bestValue': 'Best value',
    'premium.trialCta': 'Start 7-day free trial',
    'premium.cancelAnytime': 'Cancel anytime. No commitment.',
    'premium.body':
        'Coach, advanced stats, season pass, premium cosmetics, widget themes, and Buddy Pass in one layer.',
    'premium.featureCoach': 'Algorithmic coach',
    'premium.featureStats': 'Advanced stats',
    'premium.featureSeason': 'Season pass',
    'premium.featureCosmetics': 'Premium cosmetics',
    'premium.activateDemo': 'Enable demo Plus',
    'premium.clearDemo': 'Disable demo Plus',
    'premium.openSeason': 'Season Pass',
    'premium.openCrates': 'Crates',
    'premium.widgetThemes': 'Widget / lock-screen themes',
    'premium.widgetClassic': 'Classic widget',
    'premium.widgetPreview': '{done}/{goal} min today',
    'premium.syncError': 'Plus state could not be synced right now.',
    'premium.backendTitle': 'Plus sync status',
    'premium.backendOnline':
        'Online account connected; Plus is read from server.',
    'premium.backendOffline':
        'No online account connected; only local demo state is active right now.',
    'premium.account': 'Account',
    'premium.notSignedIn': 'Not signed in',
    'premium.status': 'Status',
    'premium.statusActive': 'Active',
    'premium.statusInactive': 'Inactive',
    'premium.refresh': 'Refresh Plus status',

    'buddy.title': 'Buddy Pass',
    'buddy.body':
        'Each active Plus account can send one 30-day pass per month. The receiver does not need to be new; each account can redeem only once. If your friend reaches 180 real focus minutes, you earn the Buddy Moon Pin badge.',
    'buddy.requirements':
        'Redeeming requires a different account that is not already Plus.',
    'buddy.copy': 'Copy',
    'buddy.copied': 'Buddy Pass code copied.',
    'buddy.create': 'Create Buddy Pass',
    'buddy.created': 'Buddy Pass is ready.',
    'buddy.createFailed': 'Buddy Pass could not be created.',
    'buddy.monthlyUsed': 'This month’s Buddy Pass has already been used.',
    'buddy.activePremiumRequired':
        'Active Plus is required to send a Buddy Pass.',
    'buddy.authenticationRequired':
        'You need to sign in online to use Buddy Pass.',
    'buddy.redeemLabel': 'Buddy Pass code',
    'buddy.redeem': 'Redeem',
    'buddy.redeemed': 'Buddy Pass redeemed.',
    'buddy.invalid': 'That code could not be used.',

    'season.title': 'Focus Pass',
    'season.progress': '{minutes} real focus minutes',
    'season.freeTrack': 'Free track',
    'season.premiumTrack': 'Plus track',
    'season.unlockAt': 'Unlocks at {minutes} min',
    'season.claim': 'Claim',
    'season.claimed': 'Claimed',
    'season.previewTitle': 'Monthly season is live',
    'season.previewBody': '{minutes} real focus minutes logged.',
    'season.open': 'Open',

    'crates.title': 'Crates',
    'crates.wallet': '{points} points · {coin} coin · {shards} shards',
    'crates.collection': 'Collection',
    'crates.owned': '{count} owned',
    'crates.price': '{points} points',
    'crates.plusOnly': 'Plus',
    'crates.buy': 'Buy',
    'crates.open': 'Open',
    'crates.opening': 'Opening crate',
    'crates.rolling': 'What will drop?',
    'crates.economyNote':
        'Crates are bought with points and only drop cosmetics. Coin stays for shop purchases; leaderboard rank still comes from real focus minutes.',

    'coach.starterHeadline': 'Safe starting point',
    'coach.starterReason':
        'There is little data yet, so I am using a balanced block; a few real sessions will personalize the rhythm.',
    'coach.historyHeadline': 'Based on your recent rhythm',
    'coach.bestHourHeadline': 'Your strongest window is {hour}:00',
    'coach.shorterReason':
        'Early endings increased in {category}, so a cleaner {minutes}-minute block looks wiser.',
    'coach.historyReason':
        'Blending your last {sessions} {category} sessions makes {minutes} minutes look like the most balanced option.',

    'settings.title': 'Settings',
    'settings.displayName': 'Display name',
    'settings.profileShareBaseUrl': 'Profile share address',
    'settings.profileShareBaseUrlHint': 'E.g. https://your-domain.com',
    'settings.privacy': 'Privacy',
    'settings.profileStatsVisibility': 'Show stats on profile',
    'settings.profileStatsVisibilityBody':
        'When off, profile visitors cannot see total time, streak, or sessions.',
    'settings.blockedUsers': 'Blocked users',
    'settings.noBlockedUsers': 'No blocked users.',
    'settings.unblock': 'Unblock',
    'settings.language': 'Language',
    'settings.turkish': 'Turkish',
    'settings.english': 'English',
    'settings.theme': 'Theme',
    'settings.system': 'System',
    'settings.light': 'Light',
    'settings.dark': 'Dark mode',
    'settings.dnd': 'Do not disturb reminder',
    'settings.petNotifications': 'Pet notifications',
    'settings.dailyGoalReminder': 'Daily target reminder',
    'settings.dailyGoalReminderBody': 'Remind every day at {time}.',
    'settings.changeReminderTime': 'Change reminder time',
    'settings.monthlyGoal': 'Monthly goal',
    'settings.monthlyGoalBody': 'This Month target.',
    'settings.save': 'Save settings',
    'settings.saved': 'Settings saved',
    'settings.offline': 'Offline use is on. Data is kept on this device.',
    'settings.server': 'Sync is on.',
    'settings.authTitle': 'Account',
    'settings.authSignedIn': 'Signed in with {provider}: {email}',
    'settings.authSignedOut': 'Not signed in yet.',
    'settings.signOut': 'Sign out',
    'settings.openLogin': 'Open sign-in screen',
    'settings.deleteAccount': 'Delete account',
    'settings.deleteAccountBody':
        'This cannot be undone. Your account, focus minutes, profile, pet progress, tasks, and synced Catudy data will be permanently deleted.',
    'settings.deleteAccountConfirm': 'Delete account',
    'settings.demoWallet': 'Demo Wallet',
    'settings.demoWalletBody':
        'Tops coin up to 5000 and points up to 2500 for shop testing. Purchased items are kept.',
    'settings.demoWalletButton': 'Load demo wallet',
    'settings.demoWalletLoaded': 'Demo wallet loaded.',

    'appLock.title': 'App Lock',
    'appLock.header': 'Focus unlocks',
    'appLock.headerBody':
        'Catudy keeps selected apps closed until the focus target is complete.',
    'appLock.masterSwitch': 'App lock enabled',
    'appLock.masterSwitchBody':
        'When off, Catudy lock screens and location rules are inactive.',
    'appLock.permissions': 'Permissions',
    'appLock.permissionsBody':
        'Catudy checks the permissions needed for app tracking, lock screens, and location rules.',
    'appLock.usageAccess': 'Usage access',
    'appLock.overlayPermission': 'Display over apps',
    'appLock.locationPermission': 'Location',
    'appLock.backgroundLocationPermission': 'Background location',
    'appLock.allowed': 'Allowed',
    'appLock.open': 'Open',
    'appLock.androidOnly': 'App lock is not supported on this device.',
    'appLock.noInstalledApps': 'Could not read installed apps.',
    'appLock.loadingApps': 'Loading apps...',
    'appLock.lockedApps': 'Locked apps',
    'appLock.addApp': 'Add app',
    'appLock.noLockedApps': 'No locked apps yet.',
    'appLock.searchApps': 'Search apps',
    'appLock.requiredMinutes': '{minutes} min focus',
    'appLock.unlockedToday': 'Unlocked today',
    'appLock.startFocus': 'Start focus',
    'appLock.limit': '{used}/{limit} free limit',
    'appLock.plusUnlimited': 'Unlimited with Catudy Plus',
    'appLock.plusLimit': 'Catudy Plus for more apps',
    'appLock.limitReached': 'Free limit reached.',
    'appLock.locations': 'Location locks',
    'appLock.addLocation': 'Add location',
    'appLock.noLocations': 'No location locks yet.',
    'appLock.locationLimit': '{used}/{limit} free locations',
    'appLock.plusLocationLimit': 'Catudy Plus for more locations',
    'appLock.locationLimitReached': 'Free location limit reached.',
    'appLock.strictLocation':
        'Keep apps closed inside selected locations; they open when the location rule turns off.',
    'appLock.locationDetails': '{radius} m radius',
    'appLock.locationName': 'Location name',
    'appLock.searchLocation': 'Search location',
    'appLock.searchLocationHint': 'Address, school, cafe, or neighborhood',
    'appLock.locationSearchNoResults': 'No matching location found.',
    'appLock.locationSearchFailed': 'Location search is unavailable right now.',
    'appLock.useCurrentLocation': 'My location',
    'appLock.currentLocationUnavailable':
        'Could not read location. Check permissions or pick a point on the map.',
    'appLock.tapMapHint': 'Tap the map to choose the location.',
    'appLock.selectedCoordinates': 'Selected location: {lat}, {lng}',
    'appLock.defaultLocationName': 'Focus area',
    'appLock.radiusMeters': 'Radius: {radius} m',
    'appLock.saveLocation': 'Save location',
    'settings.widgetSettingsTitle': 'Widget Settings',
    'settings.widgetSettingsBody':
        'Configure home screen widgets and shortcuts.',
    'widget.previewTitle': 'Widget Preview',
    'widget.petLockLabel': 'Show Pet',
    'widget.petLockFollowActive': 'Follow active pet',
    'widget.shortcutCategoryLabel': 'Quick Start Category',
    'widget.pinWidgetButton': 'Add Widget to Home Screen',
    'widget.pinWidgetSuccess': 'Widget pinning request sent!',
    'widget.pinWidgetFailed': 'Could not add widget.',
    'widget.tabPet': 'Pet',
    'widget.tabProgress': 'Goal',
    'widget.tabShortcut': 'Shortcut',
    'widget.kind.pet': 'Pet',
    'widget.kind.goal': 'Goal',
    'widget.kind.shortcut': 'Focus',
    'widget.kind.streak': 'Streak',
    'widget.kind.wallet': 'Wallet',
    'widget.configurations': 'Widget Options',
    'widget.petMood': 'Mood',
    'widget.petHunger': 'Hunger',
    'widget.petEnergy': 'Energy',
    'widget.daysStreak': 'Days Streak',
    'widget.dailyGoalTitle': 'Daily Goal',
    'widget.goalCompleted': 'Goal Completed! 🎉',
    'widget.completed': 'Completed',
    'widget.quickFocus': 'Start quick focus',
    'widget.minLeft': 'min left',
    'widget.idle': 'Ready',

    'lobby.title': 'Lobby',
    'lobby.chooseFlow': 'Choose whether to create a lobby or join one.',
    'lobby.createTitle': 'Create Lobby',
    'lobby.joinTitle': 'Join Lobby',
    'lobby.roomTitle': 'Lobby Room',
    'lobby.durationSetup': 'Choose focus duration or enter minutes manually.',
    'lobby.customMinutes': 'Minutes',
    'lobby.selectedDuration': 'Selected duration: {minutes} minutes',
    'lobby.noActiveLobby': 'No active lobby. Create one or join by code first.',
    'lobby.copyCode': 'Copy code',
    'lobby.codeCopied': 'Lobby code copied.',
    'lobby.shareInvite': 'Share lobby invite',
    'lobby.inviteText': 'Join my Catudy lobby. Code: {code}',
    'lobby.code': 'Join code: {code}',
    'lobby.onlineBackend': 'Online lobby is active. State syncs with Supabase.',
    'lobby.offlineBackend':
        'Supabase is not configured. Demo/offline lobby is being used for now.',
    'lobby.create': 'Create online lobby',
    'lobby.join': 'Join by code',
    'lobby.joinCode': 'Lobby code',
    'lobby.leave': 'Leave lobby',
    'lobby.enterCode': 'Enter a lobby code.',
    'lobby.demoMode':
        'No online config was found, so a demo lobby opened. Real lobbies need Supabase URL and anon key.',
    'lobby.onlyOwnerCanStart': 'Only the lobby owner can start the session.',
    'lobby.waitForSecondMember':
        'At least two people must be in the lobby to start.',
    'lobby.waitForReady': 'Everyone must be ready to start.',
    'lobby.owner': 'owner',
    'lobby.online': 'online',
    'lobby.offline': 'offline',
    'lobby.notReady': 'Not ready',
    'lobby.ready': 'Ready',
    'lobby.start': 'Start sync',
    'lobby.breakVote': 'Break vote',
    'lobby.breakVoteStatus': 'Yes: {yes}/{total} · No: {no}/{total}',
    'lobby.breakQuestion': 'Take a break? Votes sync with the lobby.',

    'tour.barrier': 'Catudy intro tour',
    'tour.homeTitle': 'This is the home screen',
    'tour.homeBody':
        "Track today's focus time, streak, reminders, and a short pet status here.",
    'tour.focusTitle': 'Focus starts here',
    'tour.focusBody':
        'Tap the start focus button to choose a category and duration. Real sessions earn points, coin, and pet progress.',
    'tour.calendarTitle': 'Calendar',
    'tour.calendarBody':
        'Add manual records to past days, and create reminders with your own text for today or future days.',
    'tour.statsTitle': 'Stats',
    'tour.statsBody':
        'See your focus rhythm by week, month, and all time. Tap charts to open short explanations.',
    'tour.petTitle': 'Pet room',
    'tour.petBody':
        'Mochi lives here. Tap happiness, hunger, and energy bars to see what they mean.',
    'tour.profileTitle': 'Profile',
    'tour.profileBody':
        'Total focus, sessions, favorite category, equipped items, and your pet summary live here.',
    'onboarding.nameTitle': 'Let us know you',
    'onboarding.nameBody':
        'Choose the name shown on your profile and in lobbies. You can change it later.',
    'onboarding.petTitle': 'Choose your pet',
    'onboarding.petBody':
        'Mochi is your starting companion. New pets unlock as you earn points.',
    'onboarding.goalTitle': 'Daily target',
    'onboarding.goalBody': 'Set a realistic focus-minute target for today.',
    'onboarding.friendTitle': 'Friend code',
    'onboarding.friendBody': 'Friends use this code to add you.',
    'onboarding.startTitle': 'Ready for first focus',
    'onboarding.startBody':
        'Choose a category and duration to start your first focus session.',
    'onboarding.startFocus': 'Start first focus',
    'tour.skip': 'Skip',
    'tour.finish': 'Finish',
    'tour.next': 'Next',
  };
}
